export function getTourJsonTemplate({ master = false } = {}) {
  const tour = {
    title: "",
    slug: "",
    shortDescription: "",
    city: { from: "", to: "" },
    address: { line1: "", line2: "", city: "", state: "", zip: "", country: "" },
    distance: 0,
    period: { days: 4, nights: 3 },
    startDate: "YYYY-MM-DD",
    endDate: "YYYY-MM-DD",
    photo: "https://example.com/cover.jpg",
    photos: ["https://example.com/photo-1.jpg"],
    desc: "",
    commercial: {
      version: "COMPONENTS_V1",
      currency: "INR",
      defaultBasis: {
        adults: 1,
        children: 0,
        infants: 0,
        rooms: 1,
        vehicles: 1,
        nights: 3,
        days: 4,
      },
      components: [
        {
          componentKey: "hotel-basic",
          type: "ACCOMMODATION",
          name: "Basic hotel room",
          description: "Base accommodation included in the Basic package.",
          supplierRef: "",
          replacesComponentKey: "",
          active: true,
          status: "CONFIRMED",
          pricing: {
            unit: "PER_ROOM_PER_NIGHT",
            costAmountMinor: 250000,
            sellingAmountMinor: 300000,
            currency: "INR",
          },
          details: { propertyClass: "3-star", roomType: "Standard room" },
        },
        {
          componentKey: "hotel-standard",
          type: "ACCOMMODATION",
          name: "Standard hotel room",
          description: "Accommodation used by the Standard package.",
          supplierRef: "",
          replacesComponentKey: "hotel-basic",
          active: true,
          status: "CONFIRMED",
          pricing: {
            unit: "PER_ROOM_PER_NIGHT",
            costAmountMinor: 350000,
            sellingAmountMinor: 425000,
            currency: "INR",
          },
          details: { propertyClass: "4-star", roomType: "Deluxe room" },
        },
        {
          componentKey: "hotel-premium",
          type: "ACCOMMODATION",
          name: "Premium hotel room",
          description: "Accommodation used by the Premium package.",
          supplierRef: "",
          replacesComponentKey: "hotel-basic",
          active: true,
          status: "CONFIRMED",
          pricing: {
            unit: "PER_ROOM_PER_NIGHT",
            costAmountMinor: 500000,
            sellingAmountMinor: 625000,
            currency: "INR",
          },
          details: { propertyClass: "5-star", roomType: "Premium room" },
        },
        {
          componentKey: "airport-transfer",
          type: "TRANSFER",
          name: "Airport transfers",
          description: "Private return airport transfers.",
          supplierRef: "",
          replacesComponentKey: "",
          active: true,
          status: "CONFIRMED",
          pricing: {
            unit: "PER_VEHICLE",
            costAmountMinor: 100000,
            sellingAmountMinor: 125000,
            currency: "INR",
          },
          details: { vehicleType: "Sedan", transferType: "RETURN" },
        },
        {
          componentKey: "guided-sightseeing",
          type: "SIGHTSEEING",
          name: "Guided sightseeing",
          description: "One guided sightseeing experience.",
          supplierRef: "",
          replacesComponentKey: "",
          active: true,
          status: "CONFIRMED",
          pricing: {
            unit: "PER_PERSON",
            costAmountMinor: 80000,
            sellingAmountMinor: 100000,
            currency: "INR",
          },
          details: { duration: "Full day" },
        },
        {
          componentKey: "return-flight",
          type: "FLIGHT",
          name: "Return economy flight",
          description: "Estimated return airfare; confirmation requires repricing.",
          supplierRef: "",
          replacesComponentKey: "",
          active: true,
          status: "ESTIMATED",
          pricing: {
            unit: "PER_PERSON",
            costAmountMinor: 700000,
            sellingAmountMinor: 750000,
            currency: "INR",
          },
          details: { cabinClass: "ECONOMY", origin: "", destination: "" },
        },
        {
          componentKey: "agent-service-charge",
          type: "AGENT_CHARGE",
          name: "Agency service charge",
          description: "Agency commercial charge before platform financial rules.",
          supplierRef: "",
          replacesComponentKey: "",
          active: true,
          status: "CONFIRMED",
          pricing: {
            unit: "PER_BOOKING",
            costAmountMinor: 0,
            sellingAmountMinor: 50000,
            currency: "INR",
          },
          details: null,
        },
      ],
      packages: [
        {
          packageKey: "basic",
          tier: "BASIC",
          name: "Basic",
          description: "Essential stay, transfers and sightseeing.",
          enabled: true,
          recommended: false,
          includedComponentKeys: [
            "hotel-basic",
            "airport-transfer",
            "guided-sightseeing",
            "agent-service-charge",
          ],
          optionalComponentKeys: ["hotel-standard", "hotel-premium", "return-flight"],
        },
        {
          packageKey: "standard",
          tier: "STANDARD",
          name: "Standard",
          description: "Upgraded stay with the same core itinerary.",
          enabled: true,
          recommended: true,
          includedComponentKeys: [
            "hotel-standard",
            "airport-transfer",
            "guided-sightseeing",
            "agent-service-charge",
          ],
          optionalComponentKeys: ["return-flight"],
        },
        {
          packageKey: "premium",
          tier: "PREMIUM",
          name: "Premium",
          description: "Premium accommodation and core itinerary.",
          enabled: true,
          recommended: false,
          includedComponentKeys: [
            "hotel-premium",
            "airport-transfer",
            "guided-sightseeing",
            "agent-service-charge",
          ],
          optionalComponentKeys: ["return-flight"],
        },
      ],
    },
    seasonalPricing: [],
    packageType: "fixed_departure",
    departures: [],
    flexibleConfig: {
      earliestDeparture: null,
      latestReturn: null,
      blackoutDates: [],
      pricingModel: "seasonal",
      minAdvanceBookingDays: 0,
      maxAdvanceBookingDays: null,
    },
    customConfig: {
      responseTimeframeHours: 48,
      requireDates: true,
      requireGroupSize: true,
      allowAgentDraft: true,
      allowCustomerCustomization: true,
      questionnaireFields: [],
    },
    flights: {
      included: false,
      inventoryManaged: false,
      pricePerPerson: 0,
      currency: "INR",
      departureCity: "",
      arrivalCity: "",
      airline: "",
      notes: "",
    },
    itinerary: [
      {
        day: 1,
        title: "",
        summary: "",
        activities: [""],
        structuredActivities: [
          {
            name: "",
            description: "",
            duration: "",
            price: 0,
            currency: "INR",
            included: true,
            bookable: false,
          },
        ],
        meals: [""],
        accommodation: "",
        location: "",
        notes: "",
      },
    ],
    highlights: [{ title: "", short: "", icon: "", order: 0 }],
    includedStays: [
      {
        nights: 1,
        location: "",
        propertyName: "",
        propertyClass: "",
        roomType: "",
        meals: [""],
        description: "",
        tier: "",
        pricing: { unit: null, amountMinor: null, currency: "INR" },
      },
    ],
    hotelOptions: [
      {
        optionKey: "destination-primary-hotel",
        stayKey: "destination-stay-1",
        title: "Primary destination hotel",
        description: "The package-included hotel for this itinerary stay.",
        propertyName: "Primary destination hotel",
        propertyClass: "4-star",
        location: "Destination",
        address: "Destination address",
        nights: 2,
        photos: ["https://example.com/primary-hotel.jpg"],
        amenities: ["Wi-Fi", "Restaurant", "Pool"],
        packageKeys: [],
        rooms: [
          {
            roomKey: "primary-standard",
            name: "Standard room",
            description: "Included with the Basic package.",
            bedType: "King or twin beds",
            maxAdults: 2,
            maxChildren: 1,
            meals: ["Breakfast"],
            amenities: ["Wi-Fi", "Air conditioning"],
            photos: ["https://example.com/standard-room.jpg"],
            packageKeys: ["basic"],
            available: true,
            pricing: { unit: "PER_ROOM_PER_NIGHT", amountMinor: 500000, currency: "INR" },
          },
          {
            roomKey: "primary-deluxe",
            name: "Deluxe room",
            description: "Included with the Standard package.",
            bedType: "King bed",
            maxAdults: 2,
            maxChildren: 1,
            meals: ["Breakfast", "Dinner"],
            amenities: ["Wi-Fi", "Air conditioning", "Preferred view"],
            photos: ["https://example.com/deluxe-room.jpg"],
            packageKeys: ["standard"],
            available: true,
            pricing: { unit: "PER_ROOM_PER_NIGHT", amountMinor: 750000, currency: "INR" },
          },
          {
            roomKey: "primary-suite",
            name: "Suite",
            description: "Included with the Premium package.",
            bedType: "King bed",
            maxAdults: 3,
            maxChildren: 2,
            meals: ["Breakfast", "Dinner"],
            amenities: ["Wi-Fi", "Air conditioning", "Living area"],
            photos: ["https://example.com/suite.jpg"],
            packageKeys: ["premium"],
            available: true,
            pricing: { unit: "PER_ROOM_PER_NIGHT", amountMinor: 1100000, currency: "INR" },
          },
        ],
        costLabel: "Room price",
        cost: "Calculated by the backend",
        tier: "",
        recommended: false,
        active: true,
        pricing: { unit: null, amountMinor: null, currency: "INR" },
      },
      {
        optionKey: "destination-alternative-hotel",
        stayKey: "destination-stay-1",
        title: "Alternative hotel in the same destination",
        description: "A selectable alternative for the same location and nights.",
        propertyName: "Alternative destination hotel",
        propertyClass: "4-star",
        location: "Destination",
        address: "Alternative destination address",
        nights: 2,
        photos: ["https://example.com/alternative-hotel.jpg"],
        amenities: ["Wi-Fi", "Restaurant"],
        packageKeys: [],
        rooms: [
          {
            roomKey: "alternative-standard",
            name: "Alternative standard room",
            description: "Optional room; not included in a package by default.",
            bedType: "King or twin beds",
            maxAdults: 2,
            maxChildren: 1,
            meals: ["Breakfast"],
            amenities: ["Wi-Fi", "Air conditioning"],
            photos: ["https://example.com/alternative-room.jpg"],
            packageKeys: [],
            available: true,
            pricing: { unit: "PER_ROOM_PER_NIGHT", amountMinor: 600000, currency: "INR" },
          },
        ],
        costLabel: "Room price",
        cost: "Calculated by the backend",
        tier: "",
        recommended: false,
        active: true,
        pricing: { unit: null, amountMinor: null, currency: "INR" },
      },
    ],
    cancellation: {
      policy: "",
      freeCancellationUntil: "",
      refundPercent: 100,
      depositRequired: false,
      depositPercent: null,
      depositNote: "",
      note: "",
      tiers: [{ label: "", daysBefore: 0, refundPercent: 0, description: "" }],
    },
    extras: [
      {
        title: "",
        description: "",
        price: 0,
        currency: "INR",
        priceLabel: "",
        icon: "",
        category: "",
        included: false,
        active: true,
        pricing: { unit: null, amountMinor: null, currency: "INR" },
      },
    ],
    availability: { totalSeats: null, seatsAvailable: null },
    meetingPoint: "",
    inclusions: [""],
    exclusions: [""],
    languages: [""],
    cancellationPolicy: "",
    minAge: null,
    maxAge: null,
    maxGroupSize: 1,
    group: { min: 1, max: null },
    rating: { average: 0, count: 0 },
    reviews: [{ name: "", rating: 0, comment: "" }],
    featured: false,
    trending: false,
    tags: [""],
    tagIds: [],
    isPublished: false,
    status: "draft",
    visibility: "public",
    inventorySource: "platform",
    providerName: "",
  };
  if (!master) {
    delete tour.visibility;
    delete tour.providerName;
    delete tour.inventorySource;
  }
  return JSON.stringify(tour, null, 2);
}

export function getTripJsonTemplate({ master = false } = {}) {
  const trip = {
    title: "",
    slug: "",
    category: "weekend",
    tag: "",
    location: "",
    country: "India",
    duration: "",
    startDate: "YYYY-MM-DD",
    endDate: "YYYY-MM-DD",
    dates: ["YYYY-MM-DD"],
    image: "https://example.com/cover.jpg",
    photos: ["https://example.com/photo-1.jpg"],
    description: "",
    chips: [""],
    tags: [""],
    price: { amount: 0, currency: "INR", tokenAmount: 1999, isFinal: true },
    availability: { totalSeats: null, seatsAvailable: null },
    preferences: {
      roomTypes: [{ label: "", value: "", extraPrice: 0 }],
      mealPreferences: [{ label: "", value: "", extraPrice: 0 }],
      packageTypes: [{ label: "", value: "", extraPrice: 0 }],
      drinkTypes: [{ label: "", value: "", extraPrice: 0 }],
    },
    itinerary: [{ day: 1, title: "", summary: "", location: "", activities: [""] }],
    inclusions: [""],
    exclusions: [""],
    includedStays: [
      {
        nights: 1,
        location: "",
        propertyName: "",
        propertyClass: "",
        roomType: "",
        meals: [""],
        description: "",
      },
    ],
    hotelOptions: [
      { title: "", description: "", costLabel: "Upgrade cost", cost: "", recommended: false },
    ],
    cancellation: {
      policy: "",
      tiers: [{ label: "", daysBefore: 0, refundPercent: 0, description: "" }],
    },
    extras: [
      {
        title: "",
        description: "",
        price: 0,
        currency: "INR",
        priceLabel: "",
        icon: "",
        included: false,
      },
    ],
    cancellationPolicy: "",
    featured: false,
    isListed: true,
    status: "listed",
    sortOrder: 0,
  };
  if (master) Object.assign(trip, { visibility: "public" });
  return JSON.stringify(trip, null, 2);
}
