export function getTourJsonTemplate({ master = false } = {}) {
  const tour = { title: "", city: { from: "", to: "" }, address: { line1: "", line2: "", city: "", state: "", zip: "", country: "" }, distance: 0, period: { days: 1, nights: 0 }, startDate: "YYYY-MM-DD", endDate: "YYYY-MM-DD", photo: "https://example.com/cover.jpg", photos: ["https://example.com/photo-1.jpg"], desc: "", price: { min: 0, max: 0, currency: "INR", isFinal: false, source: "manual" }, seasonalPricing: [{ seasonName: "", startDate: "YYYY-MM-DD", endDate: "YYYY-MM-DD", min: 0, max: 0, currency: "INR", isFinal: false, source: "manual", notes: "" }], itinerary: [{ day: 1, title: "", summary: "", activities: [""], meals: [""], accommodation: "", location: "", notes: "" }], highlights: [{ title: "", short: "", icon: "", order: 0 }], includedStays: [{ nights: 1, location: "", propertyName: "", propertyClass: "", roomType: "", meals: [""], description: "" }], hotelOptions: [{ title: "", description: "", costLabel: "Upgrade cost", cost: "", recommended: false }], cancellation: { policy: "", freeCancellationUntil: "", refundPercent: 100, depositRequired: false, depositPercent: null, depositNote: "", note: "", tiers: [{ label: "", daysBefore: 0, refundPercent: 0, description: "" }] }, extras: [{ title: "", description: "", price: 0, currency: "INR", priceLabel: "", icon: "", included: false }], availability: { totalSeats: null, seatsAvailable: null }, meetingPoint: "", inclusions: [""], exclusions: [""], languages: [""], cancellationPolicy: "", minAge: null, maxAge: null, maxGroupSize: 1, featured: false, tags: [""], isPublished: true, status: "published" };
  if (master) Object.assign(tour, { visibility: "public", providerName: "" });
  return JSON.stringify(tour, null, 2);
}

export function getTripJsonTemplate({ master = false } = {}) {
  const trip = { title: "", slug: "", category: "weekend", tag: "", location: "", country: "India", duration: "", startDate: "YYYY-MM-DD", endDate: "YYYY-MM-DD", dates: ["YYYY-MM-DD"], image: "https://example.com/cover.jpg", photos: ["https://example.com/photo-1.jpg"], description: "", chips: [""], tags: [""], price: { amount: 0, currency: "INR", tokenAmount: 1999, isFinal: true }, availability: { totalSeats: null, seatsAvailable: null }, preferences: { roomTypes: [{ label: "", value: "", extraPrice: 0 }], mealPreferences: [{ label: "", value: "", extraPrice: 0 }], packageTypes: [{ label: "", value: "", extraPrice: 0 }], drinkTypes: [{ label: "", value: "", extraPrice: 0 }] }, itinerary: [{ day: 1, title: "", summary: "", location: "", activities: [""] }], inclusions: [""], exclusions: [""], includedStays: [{ nights: 1, location: "", propertyName: "", propertyClass: "", roomType: "", meals: [""], description: "" }], hotelOptions: [{ title: "", description: "", costLabel: "Upgrade cost", cost: "", recommended: false }], cancellation: { policy: "", tiers: [{ label: "", daysBefore: 0, refundPercent: 0, description: "" }] }, extras: [{ title: "", description: "", price: 0, currency: "INR", priceLabel: "", icon: "", included: false }], cancellationPolicy: "", featured: false, isListed: true, status: "listed", sortOrder: 0 };
  if (master) Object.assign(trip, { visibility: "public" });
  return JSON.stringify(trip, null, 2);
}
