export default {
  "font-primary": "\"Inter\",\n  \"Poppins\",\n  system-ui,\n  -apple-system,\n  BlinkMacSystemFont,\n  \"Segoe UI\",\n  sans-serif",
  "font-secondary": "$font-primary",
  "root-font-size-desktop": "16px",
  "root-font-size-tablet": "15px",
  "root-font-size-mobile": "14px",
  "control-font-size-mobile": "14px",
  "font-size-xs": "0.76rem !default",
  "font-size-sm": "0.875rem",
  "font-size-md": "1rem",
  "font-size-lg": "1.25rem",
  "font-size-xl": "1.5rem",
  "font-size-xxl": "2rem",
  "font-size-xxxl": "2.5rem",
  "font-light": "300",
  "font-regular": "400",
  "font-medium": "500",
  "font-semibold": "600",
  "font-bold": "700",
  "font-extrabold": "800",
  "font-black": "900",
  "line-height-xs": "1.25 !default",
  "line-height-sm": "1.2",
  "line-height-md": "1.5",
  "line-height-lg": "1.75"
};
