import config from "./env.js";
import applyHideFlags from "./visibility.js";

const partnershipUrl = `${String(config.AUTH_APP_URL || config.SHELL_URL || "").replace(/\/$/, "")}/partnership`;

export default applyHideFlags({
    status: "success",
    message: "App header config loaded",
    componentData: {
        version: 1,
        ariaLabel: "Dashboard application header",
        brand: {
            logoSrc: "/favicon.png",
            darkLogoSrc: "/favicon-dark.png",
            name: "Shree Air",
            subtitle: "Tours & Travels",
            href: "/",
        },
        footer: {
            brand: "TravelsTREM",
            owner: "Shree Air Tours and Travels",
            description: "Tours · Reservations · Experiences · Management",
            logoSrc: "/favicon-dark.png",
            contacts: [
                {
                    id: "email",
                    label: "akshat.goyal@travelstrem.com",
                    href: "mailto:akshat.goyal@travelstrem.com",
                    icon: "mail",
                },
                { id: "phone", label: "+91 90576 35580", href: "tel:+919057635580", icon: "phone" },
                {
                    id: "location",
                    label: "Shree Air Tours and Travels, Jaipur",
                    href: "https://maps.app.goo.gl/ebvDhsdzAe27XRSn7",
                    target: "_blank",
                    icon: "mapPin",
                },
            ],
            sections: [
                {
                    id: "explore",
                    title: "Explore travel",
                    links: [
                        { id: "trips", label: "Trips & adventures", href: "/trevio/trips" },
                        { id: "tours", label: "Tours & packages", href: "/trevista/tours" },
                        { id: "flights", label: "Flights", href: "/trehub/flights" },
                        { id: "hotels", label: "Hotels", href: "/trehub/hotels" },
                    ],
                },
                {
                    id: "company",
                    title: "TravelsTREM",
                    links: [
                        { id: "about", label: "About us", href: "https://travelstrem.com/about" },
                        { id: "partnership", label: "Partnership", href: "https://travelstrem.com/partnership" },
                        { id: "sales", label: "Book a demo", href: "https://travelstrem.com/sales#book-demo" },
                    ],
                },
                {
                    id: "help",
                    title: "Help & inspiration",
                    links: [
                        { id: "support", label: "Help & support", href: "/help" },
                        { id: "articles", label: "Travel articles", href: "/articles" },
                    ],
                },
            ],
            socialLinks: [],
            legalLinks: [],
        },
        mobileMenu: {
            openLabel: "Open navigation",
            closeLabel: "Close navigation",
        },
        mobile: {
            profile: false,
        },
        search: {
            hide: true,
            placeholder: "Search tours, bookings, enquiries, support...",
            ariaLabel: "Search TravelsTREM",
            shortcut: "⌘ K",
            dialogLabel: "Search TravelsTrem",
            endpoint: "/search",
            minimumQueryLength: 2,
            debounceMs: 250,
            resultLimit: 6,
            inputPlaceholder: "Search tours, bookings, enquiries, support, and pages",
            prompt: "Search by name, destination, booking, enquiry, or support reference.",
            mobileTitle: "Search TravelsTrem",
            mobileBreakpoint: 768,
            desktopMaxHeight: 560,
            mobileSheetVariant: "fullscreen",
            loadingLabel: "Searching...",
            closeLabel: "Close search",
            enabled: false,
        },
        navigationTabs: {
            ariaLabel: "Primary navigation",
            items: [
                {
                    id: "home",
                    label: "Home",
                    icon: "home",
                    href: "/",
                    target: "overview",
                    activeTargets: ["overview"],
                },
                {
                    id: "dashboard",
                    label: "Dashboard",
                    icon: "management",
                    href: "/?tab=dashboard",
                    target: "dashboard",
                    activeTargets: ["dashboard"],
                },
                {
                    id: "explore",
                    label: "Explore",
                    icon: "compass",
                    action: "toggle-navigation",
                    activeTargets: [
                        "trevio",
                        "trevista",
                        "trehub",
                        "trips",
                        "tours",
                        "flights",
                        "articles",
                        "support",
                    ],
                },
                {
                    id: "about",
                    label: "About Us",
                    icon: "info",
                    href: "https://travelstrem.com/about",
                    type: "external",
                    target: "_blank",
                },
            ],
        },
        primaryAction: {
            label: "New Booking",
            ariaLabel: "Plan a new journey",
            icon: "plus",
            enabled: true,
            menu: {
                variant: "journey-menu",
                title: "Plan a Journey",
                ariaLabel: "Choose a TravelsTrem journey product",
                width: 440,
                items: [
                    {
                        id: "trips-adventures",
                        title: "Trips & Adventures",
                        description: "Treks, expeditions & events",
                        mobileIcon: "mountain",
                        tone: "primary",
                        target: "trevio",
                        ariaLabel: "Explore trips and adventures",
                    },
                    {
                        id: "tours-packages",
                        title: "Tours & Packages",
                        description: "Domestic & international",
                        mobileIcon: "beach",
                        tone: "tertiary",
                        target: "trevista",
                        ariaLabel: "Explore tours and packages",
                    },
                    {
                        id: "flights-hotels",
                        title: "Flights & Hotels",
                        description: "Flights, stays & transport",
                        mobileIcon: "plane",
                        tone: "secondary",
                        target: "trehub",
                        ariaLabel: "Search flights and hotels on Trehub",
                    },
                    {
                        id: "visas-insurance",
                        title: "Visas & Insurance",
                        description: "Visa, passport & insurance",
                        mobileIcon: "passport",
                        tone: "blue",
                        disabled: true,
                        comingSoon: true,
                        comingSoonLabel: "Coming soon",
                        ariaLabel: "Visas and insurance, coming soon",
                    },
                ],
            },
        },
        notification: {
            label: "Notifications",
            icon: "bell",
            enabled: false,
        },
        actions: [
            {
                id: "bookings",
                label: "My Bookings",
                ariaLabel: "Open My Bookings",
                icon: "calendarDays",
                target: "bookings",
                desktopOnly: true,
            },
            {
                id: "wishlist",
                label: "Wishlist",
                ariaLabel: "Open wishlist",
                icon: "heart",
                target: "favorites",
                mobileOnly: true,
            },
        ],
        themeAction: {
            placement: "profile",
            lightLabel: "Switch to light mode",
            darkLabel: "Switch to dark mode",
            lightIcon: "sun",
            darkIcon: "moon",
        },
        user: {
            fallbackName: "Traveller",
            menuLabel: "Open user menu",
            menuEnabled: true,
            items: [
                {
                    id: "my-bookings",
                    label: "My Bookings",
                    icon: "calendarDays",
                    target: "bookings",
                },
                {
                    id: "profile",
                    label: "My Profile",
                    icon: "user",
                    target: "profile",
                },
                {
                    id: "wishlist",
                    label: "Wishlist",
                    icon: "heart",
                    target: "favorites",
                },
                {
                    id: "support",
                    label: "Help & Support",
                    icon: "support",
                    target: "support",
                },
                {
                    id: "partnership",
                    label: "Partner with us",
                    icon: "briefcaseBusiness",
                    type: "external",
                    href: partnershipUrl,
                },
                {
                    id: "about",
                    label: "About Us",
                    icon: "info",
                    type: "external",
                    href: "https://travelstrem.com/about",
                    target: "_blank",
                },
                {
                    id: "logout",
                    label: "Sign Out",
                    icon: "logout",
                    action: "logout",
                },
            ],
        },
    },
});
