import React, { useEffect, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { GlobalLoader } from "@packages/trem-ui";
import { fetchData } from "@packages/trem-utils";
import { buildGlobalDashboardUrl } from "@packages/trem-utils";
import { getError, priceFrom, unwrap } from "./bookingEngine.js";

const money = (value, currency = "INR") => { try { return new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(Number(value || 0)); } catch { return `${currency} ${value || 0}`; } };

export default function BookingRecord({ mode = "summary", bookingBasePath = "" }) {
  const { bookingId } = useParams(); const navigate = useNavigate(); const [searchParams] = useSearchParams(); const product = searchParams.get("product") || "trevio"; const [record, setRecord] = useState(null); const [config, setConfig] = useState({}); const [error, setError] = useState(""); const [processing, setProcessing] = useState(false);
  useEffect(() => { Promise.all([fetchData(product === "trevio" ? `/trevio/bookings/${bookingId}` : `/bookings/${bookingId}`), fetchData(`/booking-engine-config.json?product=${encodeURIComponent(product)}&bookingId=${encodeURIComponent(bookingId)}`)]).then(([bookingResponse, configResponse]) => { if (bookingResponse?.status !== "success") throw new Error(getError(bookingResponse, "Booking could not load")); setRecord(unwrap(bookingResponse)); setConfig(unwrap(configResponse).config || unwrap(configResponse)); }).catch((err) => setError(err.message)); }, [bookingId, product]);
  if (error) return <main className="booking-engine__error"><h1>Booking</h1><p>{error}</p></main>;
  if (!record) return <GlobalLoader visible text="Loading booking..." />;
  const pricing = priceFrom(record) || record.currentQuote || {}; const currency = pricing.currency || record.priceSnapshot?.currency || "INR"; const travellers = record.travellers || record.travelers || [];
  const paymentMethods = config.paymentMethods || record.paymentConfiguration?.methods || [];
  const pay = async () => { setProcessing(true); try { const amount = pricing.tokenAmount ?? pricing.amountDue ?? pricing.remainingBalance ?? pricing.total; const endpoint = config.paymentEndpoint ? config.paymentEndpoint.replace("{bookingId}", encodeURIComponent(bookingId)) : `/bookings/${bookingId}/payment`; const response = await fetchData(endpoint, { method: "POST", body: { amount, currency, method: paymentMethods[0]?.code || paymentMethods[0]?.id || "" } }); if (response?.status !== "success") throw new Error(getError(response, "Payment failed")); setRecord(unwrap(response)); window.location.assign(buildGlobalDashboardUrl({ product, tab: "bookings" })); } catch (err) { setError(err.message); } finally { setProcessing(false); } };
  return <main className="booking-engine__page"><div className="booking-engine__content"><header><p className="booking-engine__eyebrow">{mode === "checkout" ? "Checkout" : "Booking Summary"}</p><h1>{record.trip?.title || record.trip?.name || record.tour?.title || record.bookingRef || "Booking"}</h1></header><section className="booking-engine__record"><p>Status <strong>{record.status || "Pending"}</strong></p><p>Travellers <strong>{travellers.length || record.guestsCount || 0}</strong></p>{record.assignedAgent && <p>Assigned agent <strong>{record.assignedAgent.name || record.assignedAgent.email}</strong></p>}{(record.assignedAgentRef || record.assignedAgencyRef || record.assignedPartnerAgencyRef) && <p>Agent reference <strong>{record.assignedAgentRef || record.assignedAgencyRef || record.assignedPartnerAgencyRef}</strong></p>}{record.currentQuote && <p>Quote <strong>{record.currentQuote.quoteRef || `Version ${record.currentQuote.version || ""}`}</strong></p>}{travellers.map((traveller, index) => <p key={traveller.id || index}>{traveller.firstName} {traveller.lastName}</p>)}<div className="booking-engine__breakdown">{(pricing.breakdown || pricing.items || []).map((row) => <p key={row.id || row.label}><span>{row.label || row.name}</span><strong>{money(row.amount, currency)}</strong></p>)}<p className="booking-engine__total"><span>Total</span><strong>{money(pricing.grandTotal ?? pricing.total ?? record.paymentSummary?.total, currency)}</strong></p>{pricing.tokenAmount != null && <p><span>Token Amount</span><strong>{money(pricing.tokenAmount, currency)}</strong></p>}{pricing.remainingBalance != null && <p><span>Remaining Balance</span><strong>{money(pricing.remainingBalance, currency)}</strong></p>}</div>{mode === "checkout" && <><h2>Payment Methods</h2><div className="booking-engine__payment-methods">{paymentMethods.map((item) => <span key={item.code || item.id || item}>{item.label || item.name || item}</span>)}</div><button type="button" onClick={pay} disabled={processing}>{processing ? "Processing..." : (config.payLabel || "Pay Now")}</button></>}{mode !== "checkout" && <button type="button" onClick={() => navigate(`${bookingBasePath}/bookings/${bookingId}/checkout?product=${encodeURIComponent(product)}`)}>Proceed to Checkout</button>}</section></div></main>;
}
