import { Reveal } from "@/components/animations/Reveal";
import { DemoLink } from "@/components/marketing/DemoLink";
import { SectionIntro } from "@/components/marketing/SectionIntro";
import { partnerCapabilities, partnerPlans } from "@/lib/partnership-content";

export function PartnerPlans() {
  return <section id="pricing" className="section partner-plans"><div className="shell"><Reveal><SectionIntro eyebrow="Partner plans" title={<>A workspace for today.<br /><em>Room for what comes next.</em></>} copy="Start with a focused operating workspace, then move up as your team, catalogue and customer relationships grow." /></Reveal><div className="commercial-grid">{partnerPlans.map((plan, index) => <Reveal className={`partner-plan${index === 1 ? " recommended" : ""}`} key={plan.name} delay={index * 60}><span className="plan-label">{plan.label}</span><h3>{plan.name}</h3><p>{plan.copy}</p><div className="plan-price"><strong>{plan.price}</strong><span>per month</span></div><ul className="plan-features">{plan.features.map(feature => <li key={feature}>{feature}</li>)}</ul><DemoLink label={`Discuss ${plan.name.replace("Partner ", "")}`} className={index === 1 ? "button" : "button button-secondary"} /></Reveal>)}</div><p className="pricing-note">Monthly prices exclude applicable taxes. Plan inclusions are confirmed during partner onboarding.</p></div></section>;
}

export function PartnerCapabilities() {
  return <section id="partner-trem" className="section partner-depth"><div className="shell"><Reveal><SectionIntro eyebrow="PartnerTREM + AdminTREM" title={<>Agency operations.<br /><em>Platform-wide oversight.</em></>} copy="From people and inventory to payments and delivery: the operational detail behind every traveller experience." /></Reveal><div className="partner-detail-grid">{partnerCapabilities.map((item, index) => <details key={item.name} className="partner-detail" open={index === 0 || index === 7}><summary><span>0{index + 1}</span>{item.name}<b aria-hidden="true">+</b></summary><div><h3>{item.title}</h3><p>{item.copy}</p><ul>{item.points.map(point => <li key={point}>{point}</li>)}</ul></div></details>)}</div></div></section>;
}

export function PartnerDistribution() {
  return <section id="distribution" className="section partner-distribution"><div className="shell"><Reveal><SectionIntro eyebrow="Operate and distribute" title={<>Your back office.<br /><em>Your next opportunity.</em></>} copy="The partner portal is useful even before a marketplace booking arrives. The marketplace adds a distribution layer while your agency stays at the centre of delivery." /></Reveal><div className="distribution-grid"><Reveal className="distribution-card"><span className="eyebrow">01 · Operate</span><h3>Manage the agency you already have.</h3><p>Agents, customers, tours, enquiries, quotes, bookings, payments and delivery records live in a structured workspace instead of disconnected operational tools.</p><div className="distribution-flow"><span>Team</span><i>→</i><span>Inventory</span><i>→</i><span>Delivery</span></div></Reveal><Reveal className="distribution-card" delay={90}><span className="eyebrow">02 · Distribute</span><h3>Let eligible tours reach TravelsTREM travellers.</h3><p>When a tour is ready and the agency is enrolled in the right product, the same inventory can become part of the customer-facing travel catalogue.</p><div className="distribution-flow"><span>PartnerTREM</span><i>→</i><span>Trevista</span><i>→</i><span>Travellers</span></div></Reveal></div></div></section>;
}
