// src/data/toursSeedFilled.js
// Generated list of 10 tour package objects (for frontend seeding / mocks).
// All fields filled (no nulls). Prices are realistic average ranges (INR) based on marketplace offers in 2025.

const photoPool = (() => {
    const pool = [];
    for (let n = 2; n <= 16; n++) {
        const num = String(n).padStart(2, "0");
        pool.push(`/tour-images/tour-img${num}.jpg`);
    }
    return pool;
})();

const shuffle = (arr, seed = 1) => {
    const a = arr.slice();
    let random = seed;
    const rand = () => {
        random = (random * 1664525 + 1013904223) % 4294967296;
        return random / 4294967296;
    };
    for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(rand() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
};

const pickPhotos = (index) => {
    const s = index + 7;
    const shuffled = shuffle(photoPool, s);
    return [shuffled[0], shuffled[1], shuffled[2], shuffled[3]];
};

const tours = [
    {
        _id: "t1",
        title: "Majestic Jaipur Escape",
        city: { from: "Delhi", to: "Jaipur" },
        address: {
            line1: "117 SHRIRAMPURI COLONY",
            line2: "NIWARU ROAD",
            city: "Jaipur",
            state: "Rajasthan",
            zip: "302012",
            country: "India",
        },
        distance: 550,
        period: { days: 3, nights: 2 },
        // sample running window (useful for seasonal pricing / fixed departures)
        startDate: "2025-12-01T00:00:00.000Z",
        endDate: "2026-03-31T23:59:59.000Z",
        photo: "/tour-images/tour-img07.jpg",
        photos: pickPhotos(1),
        desc:
            "Classic Jaipur package with comfortable 3-star/4-star hotel options, guided sightseeing of Amber Fort, City Palace, Jantar Mantar and local bazaars. Ideal for families and first-time visitors.",
        // base price range (per person) — approximate market averages for 3-day Jaipur packages in 2025.
        price: { min: 4999, max: 14999, currency: "INR", isFinal: false, source: "manual" },
        seasonalPricing: [
            {
                seasonName: "Winter Peak",
                startDate: "2025-12-15T00:00:00.000Z",
                endDate: "2026-01-05T23:59:59.000Z",
                min: 8999,
                max: 19999,
                currency: "INR",
                isFinal: true,
                source: "agent",
                notes: "Christmas & New Year surcharge applies",
            },
        ],
        itinerary: [
            {
                day: 1,
                title: "Arrival, Check-in & Local Walk",
                summary: "Pickup from Delhi, check-in at hotel and evening market stroll.",
                activities: ["Pickup from Delhi hotel or railway station", "Hotel check-in", "Local market walk (Johari Bazar)", "Hawa Mahal photo stop"],
                meals: ["Lunch", "Dinner"],
                accommodation: "Comfort 3-star hotel (Jaipur)",
                location: "Jaipur",
                notes: "Rooms allocated subject to availability; early check-in subject to request.",
            },
            {
                day: 2,
                title: "Forts & Palaces",
                summary: "Full-day sightseeing: Amber Fort, Jaigarh Fort, City Palace and Jantar Mantar.",
                activities: ["Amber Fort (elephant/viewpoint)", "Jaigarh Fort (panoramic views)", "City Palace tour", "Jantar Mantar observatory"],
                meals: ["Breakfast", "Lunch"],
                accommodation: "Comfort 3-star hotel (Jaipur)",
                location: "Jaipur",
                notes: "Start early to avoid crowds; admission fees included in package where specified.",
            },
            {
                day: 3,
                title: "Departure via Delhi",
                summary: "After breakfast, check-out and drive back to Delhi with optional stop at local emporium.",
                activities: ["Breakfast", "Check-out", "Drive back to Delhi, drop-off"],
                meals: ["Breakfast"],
                accommodation: "N/A",
                location: "Delhi/Jaipur Highway",
                notes: "Standard group transfer timings apply.",
            },
        ],
        highlights: [
            { title: "Amber Fort Sunrise", short: "Early-morning visit to Amber Fort", icon: "fort", order: 1 },
            { title: "Pink City Walk", short: "Heritage walk through bazaars and palaces", icon: "palace", order: 2 },
        ],
        availability: { totalSeats: 40, seatsAvailable: 28 },
        meetingPoint: "Pickup from selected Delhi hotels or Delhi Railway Station",
        inclusions: ["2 nights hotel (standard room)", "Daily breakfast", "Private transport for sightseeing", "Local English-speaking guide", "Entry fees as specified"],
        exclusions: ["Flights to Delhi", "Personal expenses", "Meals not mentioned", "Travel insurance"],
        languages: ["English", "Hindi"],
        cancellationPolicy: "Full refund up to 7 days before departure; 50% refund within 7 days; no refund within 48 hours.",
        minAge: 3,
        maxAge: 80,
        maxGroupSize: 40,
        reviews: [
            { name: "Akshat Goyal", rating: 5, comment: "Wonderful trip, well organized!" },
            { name: "Robert", rating: 5, comment: "Loved the experience!" },
        ],
        featured: true,
        tags: ["heritage", "family"],
        isPublished: true,
        status: "published",
        createdAt: "2025-11-13T09:43:57.121Z",
        updatedAt: "2025-11-13T09:58:52.580Z",
    },

    {
        _id: "t2",
        title: "Goa Beach Chillout",
        city: { from: "Mumbai", to: "Goa" },
        address: {
            line1: "Calangute Beach Road",
            line2: "Near Baga",
            city: "North Goa",
            state: "Goa",
            zip: "403516",
            country: "India",
        },
        distance: 590,
        period: { days: 4, nights: 3 },
        startDate: "2025-10-01T00:00:00.000Z",
        endDate: "2026-03-31T23:59:59.000Z",
        photo: "/tour-images/tour-img11.jpg",
        photos: pickPhotos(2),
        desc:
            "Relax on sandy beaches, enjoy beach shacks and nightlife; options for water-sports and heritage sightseeing. Hotel choices from budget to 4-star available.",
        // Goa market average ranges for 3-4 day packages (budget to mid-luxury).
        price: { min: 6999, max: 24999, currency: "INR", isFinal: false, source: "manual" },
        seasonalPricing: [
            {
                seasonName: "Peak Season (Dec - Jan)",
                startDate: "2025-12-15T00:00:00.000Z",
                endDate: "2026-01-10T23:59:59.000Z",
                min: 14999,
                max: 39999,
                currency: "INR",
                isFinal: true,
                source: "agent",
                notes: "Higher rates during Christmas & New Year",
            },
        ],
        itinerary: [
            {
                day: 1,
                title: "Arrival & Beach Time",
                summary: "Arrival in Goa, transfer to resort and relax at the beach.",
                activities: ["Airport pickup", "Resort check-in", "Evening beach time at Calangute/Baga"],
                meals: ["Dinner"],
                accommodation: "Beach resort (3-star/4-star options)",
                location: "Calangute/Baga",
                notes: "Optional sunset cruise can be added.",
            },
            {
                day: 2,
                title: "Water Sports & Sightseeing",
                summary: "Choice of water-sports or south Goa sightseeing.",
                activities: ["Parasailing (optional)", "Jet Ski (optional)", "Visit to Fort Aguada or local markets"],
                meals: ["Breakfast", "Lunch"],
                accommodation: "Beach resort",
                location: "Goa",
                notes: "Water-sports charged extra unless included.",
            },
            {
                day: 3,
                title: "Leisure & Nightlife",
                summary: "Relax by day and enjoy Goa's nightlife at popular shacks.",
                activities: ["Day at leisure", "Sunset party at beach shack"],
                meals: ["Breakfast", "Dinner"],
                accommodation: "Beach resort",
                location: "North Goa",
                notes: "Age restrictions may apply at some venues for alcohol.",
            },
            {
                day: 4,
                title: "Departure",
                summary: "Check-out and transfer to Goa airport or Mumbai by road (if arranged).",
                activities: ["Breakfast", "Check-out", "Airport transfer"],
                meals: ["Breakfast"],
                accommodation: "N/A",
                location: "Goa",
                notes: "Return transfers depend on package selection.",
            },
        ],
        highlights: [
            { title: "Sunset Parties", short: "Nightlife and beach parties", icon: "party", order: 1 },
            { title: "Water Sports", short: "Parasailing, jet-ski and more", icon: "surf", order: 2 },
        ],
        availability: { totalSeats: 30, seatsAvailable: 12 },
        meetingPoint: "Goa Airport or pre-arranged hotel pickup",
        inclusions: ["3 nights hotel (standard room)", "Daily breakfast as specified", "Airport transfers (point-to-point)", "Selected sightseeing or water-sports as per package"],
        exclusions: ["Alcoholic beverages", "Personal expenses & tips", "Optional activities unless specified", "Travel insurance"],
        languages: ["English", "Hindi", "Portuguese (on request)"],
        cancellationPolicy: "50% refund if cancelled 7 days before start; no refund within 48 hours of departure for peak dates.",
        minAge: 12,
        maxAge: 75,
        maxGroupSize: 30,
        reviews: [{ name: "Sara", rating: 4, comment: "Great vibe and food" }],
        featured: false,
        tags: ["beach", "adventure"],
        isPublished: true,
        status: "published",
        createdAt: "2025-06-21T07:20:00.000Z",
        updatedAt: "2025-09-01T10:00:00.000Z",
    },

    {
        _id: "t3",
        title: "Himalayan Trek — Manali Short Trek",
        city: { from: "Chandigarh", to: "Manali" },
        address: {
            line1: "Mall Road",
            line2: "Old Manali",
            city: "Manali",
            state: "Himachal Pradesh",
            zip: "175131",
            country: "India",
        },
        distance: 540,
        period: { days: 5, nights: 4 },
        startDate: "2025-05-01T00:00:00.000Z",
        endDate: "2025-11-30T23:59:59.000Z",
        photo: "/tour-images/tour-img09.jpg",
        photos: pickPhotos(3),
        desc:
            "Beginner-friendly Himalayan trek with experienced guides, village homestays and riverside camping. Includes guide, cook and basic camping gear.",
        price: { min: 12999, max: 24999, currency: "INR", isFinal: false, source: "manual" },
        seasonalPricing: [
            {
                seasonName: "Summer Trek Window",
                startDate: "2025-05-01T00:00:00.000Z",
                endDate: "2025-09-30T23:59:59.000Z",
                min: 13999,
                max: 25999,
                currency: "INR",
                isFinal: true,
                source: "agent",
                notes: "Includes camping and guide; higher during peak summer months.",
            },
        ],
        itinerary: [
            { day: 1, title: "Arrive Manali", summary: "Check-in and briefing", activities: ["Pickup from Chandigarh/Bus Stand", "Hotel check-in", "Safety briefing"], meals: ["Dinner"], accommodation: "Guesthouse (Manali)", location: "Manali", notes: "Local transport included." },
            { day: 2, title: "Start Trek", summary: "Trek to first campsite", activities: ["Trek to campsite (4-6 hrs)", "Camp setup", "Dinner around campfire"], meals: ["Breakfast", "Dinner"], accommodation: "Tented camp", location: "Hills near Manali", notes: "Moderate fitness recommended." },
            { day: 3, title: "Trek & Village Visit", summary: "Scenic trekking with village visit", activities: ["Trek", "Village interaction", "Photography stops"], meals: ["Breakfast", "Lunch", "Dinner"], accommodation: "Tented camp", location: "Himalayan trail", notes: "Weather-dependent schedule." },
            { day: 4, title: "Return to Manali", summary: "Short trek out & return to Manali", activities: ["Trek out", "Return transport to Manali"], meals: ["Breakfast", "Lunch"], accommodation: "Guesthouse (Manali)", location: "Manali", notes: "Hot showers available at guesthouse." },
            { day: 5, title: "Departure", summary: "Breakfast and onward travel", activities: ["Breakfast", "Drop to Chandigarh/Bus Stand"], meals: ["Breakfast"], accommodation: "N/A", location: "Manali/Chandigarh", notes: "Check-out by 10:00 local time." },
        ],
        highlights: [
            { title: "Riverside Camping", short: "Camp beside Himalayan streams", icon: "camp", order: 1 },
            { title: "Local Villages", short: "Meet local villagers and culture", icon: "village", order: 2 },
        ],
        availability: { totalSeats: 16, seatsAvailable: 8 },
        meetingPoint: "Manali Bus Stand / Main Square (exact pickup points shared on booking)",
        inclusions: ["Guides and porters", "Camping gear and tents", "Meals on trek (all meals)", "First-aid kit"],
        exclusions: ["Transport to Manali", "Personal insurance", "Tips for guides"],
        languages: ["English", "Hindi"],
        cancellationPolicy: "Full refund up to 10 days before start; 50% refund within 10 days; no refund within 48 hours.",
        minAge: 16,
        maxAge: 60,
        maxGroupSize: 16,
        reviews: [{ name: "Ravi", rating: 5, comment: "Brilliant guides and route" }],
        featured: true,
        tags: ["trekking", "adventure"],
        isPublished: true,
        status: "published",
        createdAt: "2025-03-11T11:11:11.000Z",
        updatedAt: "2025-04-01T09:00:00.000Z",
    },

    {
        _id: "t4",
        title: "Kerala Backwaters — Alleppey Houseboat",
        city: { from: "Kochi", to: "Alleppey" },
        address: {
            line1: "Alleppey Backwaters",
            line2: "Near Boat Jetty",
            city: "Alappuzha",
            state: "Kerala",
            zip: "688011",
            country: "India",
        },
        distance: 60,
        period: { days: 2, nights: 1 },
        startDate: "2025-01-01T00:00:00.000Z",
        endDate: "2026-12-31T23:59:59.000Z",
        photo: "/tour-images/tour-img12.jpg",
        photos: pickPhotos(4),
        desc:
            "Overnight houseboat cruise in Kerala's backwaters with traditional Kerala meals, village views and calm waterways. Suitable for couples and families seeking relaxation.",
        price: { min: 5999, max: 14999, currency: "INR", isFinal: true, source: "agent" },
        seasonalPricing: [],
        itinerary: [
            { day: 1, title: "Board Houseboat", summary: "Boarding and cruise through backwaters", activities: ["Board houseboat", "Traditional Kerala dinner on board", "Evening village views"], meals: ["Dinner"], accommodation: "Private houseboat cabin", location: "Alleppey backwaters", notes: "Fresh seafood available on request." },
            { day: 2, title: "Disembark & Local Sightseeing", summary: "After breakfast disembark and short village walk", activities: ["Breakfast on board", "Disembark", "Short boat-assisted village walk"], meals: ["Breakfast"], accommodation: "N/A", location: "Alleppey", notes: "Transport to Kochi available on request." },
        ],
        highlights: [
            { title: "Houseboat Stay", short: "Authentic backwater cruise and cabin stay", icon: "boat", order: 1 },
            { title: "Local Cuisine", short: "Fresh Kerala-style meals on board", icon: "food", order: 2 },
        ],
        availability: { totalSeats: 12, seatsAvailable: 6 },
        meetingPoint: "Alleppey Jetty (embarkation point)",
        inclusions: ["One-night houseboat accommodation", "Meals on board (as specified)", "Local transfers to jetty (within Alappuzha)"],
        exclusions: ["Transport to Alleppey", "Alcoholic beverages", "Personal expenses"],
        languages: ["English", "Malayalam"],
        cancellationPolicy: "Cancel 5 days before for 75% refund; 50% refund within 5 days; no refund within 48 hours.",
        minAge: 0,
        maxAge: 85,
        maxGroupSize: 12,
        reviews: [{ name: "Meera", rating: 5, comment: "So peaceful and scenic" }],
        featured: false,
        tags: ["relax", "family"],
        isPublished: true,
        status: "published",
        createdAt: "2025-02-10T08:00:00.000Z",
        updatedAt: "2025-05-02T09:30:00.000Z",
    },

    {
        _id: "t5",
        title: "Agra Day Trip — Taj Sunrise",
        city: { from: "Delhi", to: "Agra" },
        address: {
            line1: "Near Taj East Gate",
            line2: "Taj Road",
            city: "Agra",
            state: "Uttar Pradesh",
            zip: "282001",
            country: "India",
        },
        distance: 210,
        period: { days: 1, nights: 0 },
        startDate: "2025-01-01T00:00:00.000Z",
        endDate: "2026-12-31T23:59:59.000Z",
        photo: "/tour-images/tour-img02.jpg",
        photos: pickPhotos(5),
        desc: "Early-morning Taj Mahal visit with private transport, guided tour of Agra Fort and breakfast near Taj — perfect for quick trips from Delhi.",
        price: { min: 2499, max: 4499, currency: "INR", isFinal: true, source: "manual" },
        seasonalPricing: [],
        itinerary: [
            { day: 1, title: "Taj Sunrise & Agra Fort", summary: "Sunrise at Taj Mahal followed by Agra Fort visit and return to Delhi", activities: ["Pickup from Delhi hotel", "Sunrise at Taj Mahal", "Agra Fort guided tour", "Breakfast near Taj"], meals: ["Breakfast"], accommodation: "N/A", location: "Agra", notes: "Taj timings depend on sunrise; permit and queue times vary." },
        ],
        highlights: [{ title: "Sunrise at Taj", short: "Iconic landmark at dawn", icon: "landmark", order: 1 }],
        availability: { totalSeats: 40, seatsAvailable: 20 },
        meetingPoint: "Pickup from Delhi hotel (pre-booked)",
        inclusions: ["Private transport (A/C vehicle)", "Taj Mahal entrance fee (standard ticket)", "Guided tour of Agra Fort", "Breakfast (coffee & light meal)"],
        exclusions: ["Personal expenses", "Any upgrades or private photo fees"],
        languages: ["English", "Hindi"],
        cancellationPolicy: "Full refund up to 48 hours before departure; 50% refund within 48 hours; no refund within 24 hours.",
        minAge: 0,
        maxAge: 90,
        maxGroupSize: 40,
        reviews: [{ name: "Anita", rating: 5, comment: "Quick and worth it" }],
        featured: false,
        tags: ["history", "short"],
        isPublished: true,
        status: "published",
        createdAt: "2025-07-05T05:00:00.000Z",
        updatedAt: "2025-07-06T06:00:00.000Z",
    },

    {
        _id: "t6",
        title: "Rishikesh Yoga & Rapids",
        city: { from: "Dehradun", to: "Rishikesh" },
        address: {
            line1: "Laxman Jhula Road",
            line2: "Tapovan",
            city: "Rishikesh",
            state: "Uttarakhand",
            zip: "249192",
            country: "India",
        },
        distance: 260,
        period: { days: 3, nights: 2 },
        startDate: "2025-01-01T00:00:00.000Z",
        endDate: "2026-12-31T23:59:59.000Z",
        photo: "/tour-images/tour-img08.jpg",
        photos: pickPhotos(6),
        desc: "A mix of yoga sessions, Ganga Aarti, guided meditation and optional white-water rafting for adventure seekers. Suitable for solo travellers and groups.",
        price: { min: 7999, max: 11999, currency: "INR", isFinal: false, source: "ai" },
        seasonalPricing: [],
        itinerary: [
            { day: 1, title: "Arrival & Aarti", summary: "Arrive and attend Ganga Aarti", activities: ["Pickup from Dehradun station", "Check-in", "Evening Ganga Aarti at Triveni Ghat"], meals: ["Dinner"], accommodation: "Ashram or guesthouse (shared/ private options)", location: "Rishikesh", notes: "Optional one-to-one yoga sessions available at extra cost." },
            { day: 2, title: "Yoga & Rafting", summary: "Morning yoga session and optional rafting in afternoon", activities: ["Sunrise yoga (1.5 hrs)", "Local sight-seeing", "Optional rafting (class II-III)"], meals: ["Breakfast", "Lunch"], accommodation: "Guesthouse", location: "Rishikesh", notes: "Rafting requires waiver and minimum age restrictions by operators." },
            { day: 3, title: "Departure", summary: "Morning meditation and departure", activities: ["Morning meditation", "Check-out and drop to Dehradun"], meals: ["Breakfast"], accommodation: "N/A", location: "Rishikesh/Dehradun", notes: "Check-out by 11:00 unless late-checkout added." },
        ],
        highlights: [
            { title: "Ganga Aarti", short: "Spiritual riverside ritual", icon: "aarti", order: 1 },
            { title: "White-water Rafting", short: "Optional adrenaline activity", icon: "raft", order: 2 },
        ],
        availability: { totalSeats: 20, seatsAvailable: 10 },
        meetingPoint: "Dehradun Railway Station pickup (timings shared after booking)",
        inclusions: ["2 nights accommodation (per package)", "Daily breakfast and selected meals", "One group yoga session", "Transfers within itinerary"],
        exclusions: ["Rafting fee (optional)", "Personal insurance", "Airport transfers unless specified"],
        languages: ["English", "Hindi"],
        cancellationPolicy: "Partial refund depending on notice; full refund if cancelled 14 days prior (standard policy).",
        minAge: 12,
        maxAge: 60,
        maxGroupSize: 20,
        reviews: [{ name: "Priya", rating: 4, comment: "Perfect blend of calm & thrill" }],
        featured: false,
        tags: ["wellness", "adventure"],
        isPublished: true,
        status: "published",
        createdAt: "2025-08-01T10:00:00.000Z",
        updatedAt: "2025-09-10T12:00:00.000Z",
    },

    {
        _id: "t7",
        title: "Udaipur Lakes & Palaces",
        city: { from: "Ahmedabad", to: "Udaipur" },
        address: {
            line1: "Lake Pichola",
            line2: "Near City Palace",
            city: "Udaipur",
            state: "Rajasthan",
            zip: "313001",
            country: "India",
        },
        distance: 395,
        period: { days: 2, nights: 1 },
        startDate: "2025-10-01T00:00:00.000Z",
        endDate: "2026-03-31T23:59:59.000Z",
        photo: "/tour-images/tour-img10.jpg",
        photos: pickPhotos(7),
        desc: "Romantic lakeside city with palaces, boat rides and cultural performances — ideal for couples and photographers.",
        price: { min: 8999, max: 17999, currency: "INR", isFinal: true, source: "agent" },
        seasonalPricing: [],
        itinerary: [
            { day: 1, title: "City Palace & Boat Ride", summary: "City Palace guided tour and sunset boat ride on Lake Pichola", activities: ["City Palace tour", "Boat ride on Lake Pichola", "Evening cultural show"], meals: ["Breakfast"], accommodation: "Lakeview hotel (standard)", location: "Udaipur", notes: "Private boat options available at extra cost." },
            { day: 2, title: "Markets & Departure", summary: "Local markets and departure to Ahmedabad", activities: ["Shopping in local bazaars", "Visit Saheliyon ki Bari"], meals: ["Breakfast"], accommodation: "N/A", location: "Udaipur", notes: "Hotel checkout by 11:00 unless extended." },
        ],
        highlights: [
            { title: "Lake Pichola Cruise", short: "Romantic sunset boat rides", icon: "boat", order: 1 },
            { title: "City Palace", short: "Royal architecture and museums", icon: "palace", order: 2 },
        ],
        availability: { totalSeats: 20, seatsAvailable: 5 },
        meetingPoint: "Hotel lobby pickup (Udaipur)",
        inclusions: ["1 night hotel (standard)", "Breakfast", "Boat ride (shared)", "City Palace entry"],
        exclusions: ["Dinner", "Private boat upgrade", "Personal expenses"],
        languages: ["English", "Hindi"],
        cancellationPolicy: "No refund within 48 hours of start; partial refunds earlier as per policy.",
        minAge: 0,
        maxAge: 90,
        maxGroupSize: 20,
        reviews: [{ name: "Nikhil", rating: 5, comment: "Picture-perfect city!" }],
        featured: true,
        tags: ["romance", "photography"],
        isPublished: true,
        status: "published",
        createdAt: "2025-04-18T09:30:00.000Z",
        updatedAt: "2025-07-01T08:15:00.000Z",
    },

    {
        _id: "t8",
        title: "Shimla Heritage Weekend",
        city: { from: "Chandigarh", to: "Shimla" },
        address: {
            line1: "Mall Road",
            line2: "Near Scandal Point",
            city: "Shimla",
            state: "Himachal Pradesh",
            zip: "171001",
            country: "India",
        },
        distance: 350,
        period: { days: 2, nights: 1 },
        startDate: "2025-10-01T00:00:00.000Z",
        endDate: "2026-03-31T23:59:59.000Z",
        photo: "/tour-images/tour-img13.jpg",
        photos: pickPhotos(8),
        desc: "Charming hill station weekend with colonial walks, toy-train optional ride and easy nature trails — family-friendly.",
        price: { min: 4999, max: 8999, currency: "INR", isFinal: true, source: "manual" },
        seasonalPricing: [],
        itinerary: [{ day: 1, title: "Shimla Walks", summary: "Mall Road and Christ Church visit", activities: ["Mall Road stroll", "Christ Church visit", "Optional toy-train (at extra cost)"], meals: ["Breakfast"], accommodation: "Heritage hotel (Shimla)", location: "Shimla", notes: "Weather may be cool; carry warm clothes." }],
        highlights: [{ title: "Toy Train", short: "Scenic mountain ride (subject to availability)", icon: "train", order: 1 }],
        availability: { totalSeats: 25, seatsAvailable: 15 },
        meetingPoint: "Chandigarh pickup point (exact location sent after booking)",
        inclusions: ["Transport (AC coach)", "Breakfast", "One-night hotel stay (standard)", "Local sightseeing as per itinerary"],
        exclusions: ["Lunch", "Toy train tickets", "Personal expenses"],
        languages: ["English", "Hindi"],
        cancellationPolicy: "50% refund within 5 days; no refund within 48 hours.",
        minAge: 0,
        maxAge: 90,
        maxGroupSize: 25,
        reviews: [{ name: "Gaurav", rating: 4, comment: "Pleasant weekend" }],
        featured: false,
        tags: ["hillstation", "family"],
        isPublished: true,
        status: "published",
        createdAt: "2025-01-20T07:00:00.000Z",
        updatedAt: "2025-02-25T09:00:00.000Z",
    },

    {
        _id: "t9",
        title: "Andaman Island Explorer",
        city: { from: "Port Blair", to: "Havelock Island" },
        address: {
            line1: "Havelock Jetty",
            line2: "Beachside",
            city: "Havelock Island",
            state: "Andaman & Nicobar",
            zip: "744211",
            country: "India",
        },
        distance: 240,
        period: { days: 5, nights: 4 },
        startDate: "2025-10-01T00:00:00.000Z",
        endDate: "2026-03-31T23:59:59.000Z",
        photo: "/tour-images/tour-img14.jpg",
        photos: pickPhotos(9),
        desc: "Island-hopping itinerary with snorkeling, scuba (optional), Radhanagar beach and local island culture. Mid-range to premium resorts available.",
        price: { min: 24999, max: 44999, currency: "INR", isFinal: true, source: "agent" },
        seasonalPricing: [],
        itinerary: [
            { day: 1, title: "Arrival Port Blair", summary: "Arrive Port Blair, local museum and light show", activities: ["Port Blair arrival", "Coral Museum visit", "Cellular Jail light & sound show"], meals: ["Dinner"], accommodation: "Port Blair hotel", location: "Port Blair", notes: "Timing of light show varies seasonally." },
            { day: 2, title: "Havelock Transfer", summary: "Ferry to Havelock and beach time", activities: ["Ferry transfer (pre-booked)", "Beach time at Radhanagar"], meals: ["Breakfast"], accommodation: "Beach resort (Havelock)", location: "Havelock Island", notes: "Ferry timing subject to marine conditions." },
        ],
        highlights: [
            { title: "Scuba & Snorkel", short: "Explore coral reefs (optional, charged extra)", icon: "scuba", order: 1 },
            { title: "Radhanagar Beach", short: "Iconic white-sand beach & sunset", icon: "sunset", order: 2 },
        ],
        availability: { totalSeats: 12, seatsAvailable: 4 },
        meetingPoint: "Port Blair Airport pickup",
        inclusions: ["Transfers (airport & inter-island ferries as specified)", "4 nights accommodation (as per package)", "Selected activities (snorkeling trips depending on package)"],
        exclusions: ["Scuba certification fee", "Flights to Port Blair", "Personal expenses"],
        languages: ["English"],
        cancellationPolicy: "Non-refundable within 7 days of start; earlier cancellations attract partial refunds as per policy.",
        minAge: 12,
        maxAge: 60,
        maxGroupSize: 12,
        reviews: [{ name: "Karan", rating: 5, comment: "Like a postcard — stunning!" }],
        featured: true,
        tags: ["beach", "diving"],
        isPublished: true,
        status: "published",
        createdAt: "2025-05-10T06:30:00.000Z",
        updatedAt: "2025-06-15T07:45:00.000Z",
    },

    {
        _id: "t10",
        title: "Leh-Ladakh Roadtrip (7 Days)",
        city: { from: "Manali", to: "Leh" },
        address: {
            line1: "Leh Market",
            line2: "Near Leh Palace",
            city: "Leh",
            state: "Ladakh",
            zip: "194101",
            country: "India",
        },
        distance: 480,
        period: { days: 7, nights: 6 },
        startDate: "2025-05-01T00:00:00.000Z",
        endDate: "2025-09-30T23:59:59.000Z",
        photo: "/tour-images/tour-img16.jpg",
        photos: pickPhotos(10),
        desc: "Classic Leh-Ladakh roadtrip with Pangong Lake, Nubra Valley, high passes and acclimatisation days. Comfortable stays with local guides.",
        price: { min: 44999, max: 79999, currency: "INR", isFinal: true, source: "agent" },
        seasonalPricing: [
            {
                seasonName: "Summer Window",
                startDate: "2025-05-01T00:00:00.000Z",
                endDate: "2025-09-30T23:59:59.000Z",
                min: 44999,
                max: 74999,
                currency: "INR",
                isFinal: true,
                source: "agent",
                notes: "Summer window pricing applies; remote logistics included.",
            },
        ],
        itinerary: [
            { day: 1, title: "Arrive & Acclimatize", summary: "Light walk and market visit to help acclimatise.", activities: ["Local market walk", "Short acclimatisation walks"], meals: ["Dinner"], accommodation: "Leh hotel (standard)", location: "Leh", notes: "Drink plenty of water and rest to avoid altitude sickness." },
            { day: 2, title: "Pangong Lake", summary: "Drive to Pangong with sightseeing en route", activities: ["Drive to Pangong (long drive)", "Sunset at Pangong Lake"], meals: ["Breakfast", "Dinner"], accommodation: "Pangong camp/tented stay", location: "Pangong", notes: "Long driving day; bring warm layers." },
        ],
        highlights: [
            { title: "Pangong Lake", short: "Azure saline lake with dramatic colours", icon: "lake", order: 1 },
            { title: "Nubra Valley", short: "Sand dunes and scenic valleys", icon: "desert", order: 2 },
        ],
        availability: { totalSeats: 10, seatsAvailable: 2 },
        meetingPoint: "Manali pickup point or Leh Airport (depending on itinerary option)",
        inclusions: ["Transport (4x4/tempo traveller as per group)", "Guide and local permits (Inner Line Permit)", "Selected meals and accommodation as specified"],
        exclusions: ["Flights to Manali/Leh", "Personal insurance", "Medical expenses due to AMS"],
        languages: ["English"],
        cancellationPolicy: "Non-refundable within 14 days of start; earlier cancellations subject to partial refunds.",
        minAge: 16,
        maxAge: 65,
        maxGroupSize: 10,
        reviews: [{ name: "Aditya", rating: 5, comment: "An unforgettable landscape." }],
        featured: true,
        tags: ["roadtrip", "adventure"],
        isPublished: true,
        status: "published",
        createdAt: "2025-03-01T04:00:00.000Z",
        updatedAt: "2025-08-01T05:30:00.000Z",
    },
];

export default tours;
