export const TRIP_TYPE = Object.freeze({
    ONE_WAY: "ONE_WAY",
    ROUND_TRIP: "ROUND_TRIP",
    MULTI_CITY: "MULTI_CITY",
});

export const CABIN = Object.freeze({
    ECONOMY: "ECONOMY",
    PREMIUM_ECONOMY: "PREMIUM_ECONOMY",
    BUSINESS: "BUSINESS",
    FIRST: "FIRST",
});

export const PASSENGER_TYPE = Object.freeze({
    ADULT: "ADULT",
    CHILD: "CHILD",
    INFANT: "INFANT",
});

export const FARE_BRAND = Object.freeze({ SAVER: "SAVER", VALUE: "VALUE", FLEX: "FLEX" });
export const AVAILABILITY_STATUS = Object.freeze({
    AVAILABLE: "AVAILABLE",
    LIMITED: "LIMITED",
    SOLD_OUT: "SOLD_OUT",
});
export const REVALIDATION_STATUS = Object.freeze({
    CONFIRMED: "CONFIRMED",
    PRICE_CHANGED: "PRICE_CHANGED",
    FARE_UNAVAILABLE: "FARE_UNAVAILABLE",
    FLIGHT_UNAVAILABLE: "FLIGHT_UNAVAILABLE",
    SEARCH_EXPIRED: "SEARCH_EXPIRED",
});
export const FLIGHT_BOOKING_STATUS = Object.freeze({
    PENDING: "PENDING",
    PAYMENT_PENDING: "PAYMENT_PENDING",
    CONFIRMED: "CONFIRMED",
    TICKETED: "TICKETED",
    FAILED: "FAILED",
    CANCELLED: "CANCELLED",
    REFUND_PENDING: "REFUND_PENDING",
    REFUNDED: "REFUNDED",
});

export const SEAT_STATUS = Object.freeze({
    AVAILABLE: "AVAILABLE",
    OCCUPIED: "OCCUPIED",
    BLOCKED: "BLOCKED",
    RESERVED: "RESERVED",
});

export const PROVIDER_ERRORS = Object.freeze({
    PRICE_CHANGED: "PRICE_CHANGED",
    SEAT_UNAVAILABLE: "SEAT_UNAVAILABLE",
    FARE_UNAVAILABLE: "FARE_UNAVAILABLE",
    FLIGHT_UNAVAILABLE: "FLIGHT_UNAVAILABLE",
    PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
    BOOKING_FAILED: "BOOKING_FAILED",
});

export const FLIGHT_SEARCH_TTL_SECONDS = 15 * 60;
export const TRIP_TYPES = Object.values(TRIP_TYPE);
export const CABINS = Object.values(CABIN);
export const BOOKING_STATUSES = Object.values(FLIGHT_BOOKING_STATUS);
