import mongoose from "mongoose";
import config from "../config/index.js";
import User from "../modules/auth/models/User.js";
import Tour from "../modules/tours/models/Tour.js";
import { deriveTourCommercialSummary } from "../core/financial-engine/services/tour-commercial.service.js";

const TOUR_SLUG = "rajasthan-royal-custom-signature-journey";
const INR = "INR";
const money = (rupees) => Math.round(rupees * 100);
const pricing = (unit, rupees) => ({
    unit,
    costAmountMinor: money(rupees),
    sellingAmountMinor: money(rupees),
    currency: INR,
});
const roomPricing = (rupees) => ({
    unit: "PER_ROOM_PER_NIGHT",
    amountMinor: money(rupees),
    currency: INR,
});

const component = (componentKey, type, name, unit, rupees, details = null) => ({
    componentKey,
    type,
    name,
    description: details?.description || "",
    supplierRef: details?.supplierRef || "TRAVELSTREM-CONTRACTED",
    replacesComponentKey: details?.replacesComponentKey || "",
    active: true,
    status: "CONFIRMED",
    pricing: pricing(unit, rupees),
    details,
});

const room = ({
    roomKey,
    name,
    description,
    bedType,
    maxAdults = 2,
    maxChildren = 1,
    meals,
    amenities,
    photos,
    packageKey,
    rupees,
}) => ({
    roomKey,
    name,
    description,
    bedType,
    maxAdults,
    maxChildren,
    meals,
    amenities,
    photos,
    packageKeys: packageKey ? [packageKey] : [],
    available: true,
    pricing: roomPricing(rupees),
});

const hotel = ({
    optionKey,
    title,
    propertyName,
    propertyClass,
    location,
    address,
    nights,
    photos,
    amenities,
    recommended = false,
    includedInPackages = true,
    roomPrices,
}) => ({
    optionKey,
    stayKey: `${String(location)
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")}-stay`,
    title,
    description: `${propertyName} with package-specific rooms and customer-selectable room upgrades.`,
    propertyName,
    propertyClass,
    location,
    address,
    nights,
    photos,
    amenities,
    packageKeys: [],
    rooms: [
        room({
            roomKey: `${optionKey}-standard`,
            name: "Heritage Standard Room",
            description: "Comfortable heritage room included with the Essential package.",
            bedType: "Queen bed or twin beds",
            meals: ["Breakfast"],
            amenities: ["Wi-Fi", "Air conditioning", "Tea and coffee", "Daily housekeeping"],
            photos,
            packageKey: includedInPackages ? "essential" : "",
            rupees: roomPrices.standard,
        }),
        room({
            roomKey: `${optionKey}-deluxe`,
            name: "Deluxe View Room",
            description: "Larger room with a preferred view, included with the Signature package.",
            bedType: "King bed",
            meals: ["Breakfast", "Dinner"],
            amenities: [
                "Wi-Fi",
                "Air conditioning",
                "Preferred view",
                "Minibar",
                "Daily housekeeping",
            ],
            photos,
            packageKey: includedInPackages ? "signature" : "",
            rupees: roomPrices.deluxe,
        }),
        room({
            roomKey: `${optionKey}-suite`,
            name: "Royal Suite",
            description: "Spacious suite with premium services, included with the Royal package.",
            bedType: "King bed with sofa bed",
            maxAdults: 3,
            maxChildren: 2,
            meals: ["Breakfast", "Dinner"],
            amenities: [
                "Wi-Fi",
                "Air conditioning",
                "Living area",
                "Premium view",
                "Minibar",
                "Evening turndown",
            ],
            photos,
            packageKey: includedInPackages ? "royal" : "",
            rupees: roomPrices.suite,
        }),
    ],
    costLabel: "Room price varies by package and selection",
    cost: "Calculated for your travellers and rooms",
    tier: "",
    recommended,
    active: true,
    pricing: { unit: null, amountMinor: null, currency: INR },
});

const photos = {
    hero: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1800&q=85",
    jaipur: [
        "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80",
    ],
    pushkar: [
        "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1200&q=80",
    ],
    jodhpur: [
        "https://images.unsplash.com/photo-1599661046827-dacde6976549?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1534757725210-57860f23d0c9?auto=format&fit=crop&w=1200&q=80",
    ],
    udaipur: [
        "https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
    ],
};

const commercial = {
    version: "COMPONENTS_V1",
    currency: INR,
    defaultBasis: { adults: 1, children: 0, infants: 0, rooms: 1, vehicles: 1, nights: 7, days: 8 },
    pricingPolicy: {
        feeType: "PERCENTAGE",
        feePercent: 12,
        feeAmountMinor: 0,
        gstPercent: 18,
        gstOn: "AGENT_FEE",
    },
    components: [
        component(
            "transfer-shared",
            "TRANSFER",
            "Private intercity transport",
            "PER_PERSON",
            8500,
            { description: "Air-conditioned vehicle across the complete Rajasthan circuit." },
        ),
        component(
            "stay-essential",
            "ACCOMMODATION",
            "Heritage standard rooms",
            "PER_PERSON",
            18000,
            { description: "Seven nights in the package-mapped standard rooms." },
        ),
        component("stay-signature", "ACCOMMODATION", "Deluxe view rooms", "PER_PERSON", 28500, {
            description: "Seven nights in package-mapped deluxe rooms.",
        }),
        component("stay-royal", "ACCOMMODATION", "Royal suites", "PER_PERSON", 44000, {
            description: "Seven nights in package-mapped suites with premium services.",
        }),
        component("meals-essential", "MEAL", "Daily breakfast", "PER_PERSON", 3200),
        component("meals-signature", "MEAL", "Breakfast and dinner", "PER_PERSON", 7200),
        component("meals-royal", "MEAL", "Premium half-board dining", "PER_PERSON", 11800),
        component(
            "sightseeing-essential",
            "SIGHTSEEING",
            "Essential monuments and entry fees",
            "PER_PERSON",
            4800,
        ),
        component(
            "sightseeing-signature",
            "SIGHTSEEING",
            "Expanded private sightseeing",
            "PER_PERSON",
            8500,
        ),
        component(
            "sightseeing-royal",
            "SIGHTSEEING",
            "Private signature experiences",
            "PER_PERSON",
            14500,
        ),
        component("guide-shared", "GUIDE", "Local English and Hindi guides", "PER_PERSON", 1800),
        component("guide-private", "GUIDE", "Dedicated private guide", "PER_PERSON", 6200),
        component("support", "MISCELLANEOUS", "24-hour trip assistance", "PER_PERSON", 900),
        component("insurance", "INSURANCE", "Domestic travel insurance", "PER_PERSON", 1400),
        component(
            "cooking-class",
            "ACTIVITY",
            "Private Rajasthani cooking class",
            "PER_PERSON",
            2600,
        ),
        component(
            "hot-air-balloon",
            "ACTIVITY",
            "Jaipur hot-air balloon experience",
            "PER_PERSON",
            12500,
        ),
        component("airport-transfer", "TRANSFER", "Private airport transfers", "PER_BOOKING", 3800),
        component(
            "flight-assistance",
            "FLIGHT",
            "Return flight planning assistance",
            "PER_PERSON",
            0,
            {
                description: "Flight sourcing support; airfare is quoted separately.",
                supplierRef: "ON-REQUEST",
            },
        ),
    ],
    packages: [
        {
            packageKey: "essential",
            tier: "BASIC",
            name: "Essential",
            description:
                "Heritage standard rooms, breakfast, private circuit transport and essential sightseeing.",
            enabled: true,
            recommended: false,
            includedComponentKeys: [
                "transfer-shared",
                "stay-essential",
                "meals-essential",
                "sightseeing-essential",
                "guide-shared",
                "support",
            ],
            optionalComponentKeys: [
                "insurance",
                "cooking-class",
                "hot-air-balloon",
                "airport-transfer",
                "flight-assistance",
            ],
        },
        {
            packageKey: "signature",
            tier: "STANDARD",
            name: "Signature",
            description:
                "Deluxe rooms, breakfast and dinner, expanded private sightseeing and travel insurance.",
            enabled: true,
            recommended: true,
            includedComponentKeys: [
                "transfer-shared",
                "stay-signature",
                "meals-signature",
                "sightseeing-signature",
                "guide-shared",
                "support",
                "insurance",
                "airport-transfer",
            ],
            optionalComponentKeys: ["cooking-class", "hot-air-balloon", "flight-assistance"],
        },
        {
            packageKey: "royal",
            tier: "PREMIUM",
            name: "Royal",
            description:
                "Royal suites, premium dining, private signature experiences and a dedicated guide.",
            enabled: true,
            recommended: false,
            includedComponentKeys: [
                "transfer-shared",
                "stay-royal",
                "meals-royal",
                "sightseeing-royal",
                "guide-private",
                "support",
                "insurance",
                "cooking-class",
                "airport-transfer",
            ],
            optionalComponentKeys: ["hot-air-balloon", "flight-assistance"],
        },
    ],
};

const hotelOptions = [
    hotel({
        optionKey: "jaipur-heritage-haveli",
        title: "Jaipur Heritage Haveli",
        propertyName: "Jaipur Heritage Haveli",
        propertyClass: "4-star heritage",
        location: "Jaipur",
        address: "Amer Road, Jaipur, Rajasthan",
        nights: 2,
        photos: photos.jaipur,
        amenities: ["Pool", "Restaurant", "Spa", "Wi-Fi", "Parking", "Concierge"],
        recommended: true,
        roomPrices: { standard: 5200, deluxe: 7600, suite: 11800 },
    }),
    hotel({
        optionKey: "pushkar-lakeside-retreat",
        title: "Pushkar Lakeside Retreat",
        propertyName: "Pushkar Lakeside Retreat",
        propertyClass: "4-star boutique",
        location: "Pushkar",
        address: "Lake Road, Pushkar, Rajasthan",
        nights: 1,
        photos: photos.pushkar,
        amenities: ["Lake view", "Restaurant", "Yoga deck", "Wi-Fi", "Garden"],
        roomPrices: { standard: 4400, deluxe: 6500, suite: 9800 },
    }),
    hotel({
        optionKey: "jodhpur-blue-city-palace",
        title: "Jodhpur Blue City Palace",
        propertyName: "Jodhpur Blue City Palace",
        propertyClass: "5-star heritage",
        location: "Jodhpur",
        address: "Circuit House Road, Jodhpur, Rajasthan",
        nights: 2,
        photos: photos.jodhpur,
        amenities: ["Pool", "Rooftop restaurant", "Fort view", "Spa", "Wi-Fi", "Gym"],
        roomPrices: { standard: 5800, deluxe: 8600, suite: 13500 },
    }),
    hotel({
        optionKey: "udaipur-lake-palace-retreat",
        title: "Udaipur Lake Palace Retreat",
        propertyName: "Udaipur Lake Palace Retreat",
        propertyClass: "5-star luxury",
        location: "Udaipur",
        address: "Lake Pichola Road, Udaipur, Rajasthan",
        nights: 2,
        photos: photos.udaipur,
        amenities: ["Lake view", "Infinity pool", "Fine dining", "Spa", "Wi-Fi", "Butler service"],
        recommended: true,
        roomPrices: { standard: 6800, deluxe: 9800, suite: 15800 },
    }),
    hotel({
        optionKey: "jaipur-amber-courtyard",
        title: "Jaipur Amber Courtyard",
        propertyName: "Jaipur Amber Courtyard",
        propertyClass: "5-star boutique",
        location: "Jaipur",
        address: "Kukas, Jaipur, Rajasthan",
        nights: 2,
        photos: photos.jaipur,
        amenities: ["Aravalli view", "Pool", "Restaurant", "Spa", "Wi-Fi", "Concierge"],
        includedInPackages: false,
        roomPrices: { standard: 6400, deluxe: 9100, suite: 14200 },
    }),
    hotel({
        optionKey: "udaipur-aravalli-resort",
        title: "Udaipur Aravalli Resort",
        propertyName: "Udaipur Aravalli Resort",
        propertyClass: "5-star resort",
        location: "Udaipur",
        address: "Kodiyat Road, Udaipur, Rajasthan",
        nights: 2,
        photos: photos.udaipur,
        amenities: ["Aravalli view", "Pool", "Fine dining", "Spa", "Wi-Fi", "Kids club"],
        includedInPackages: false,
        roomPrices: { standard: 7600, deluxe: 10800, suite: 16900 },
    }),
];

const itinerary = [
    [
        1,
        "Arrive in Jaipur",
        "Airport or railway pickup, hotel check-in and an evening heritage walk.",
        ["Private arrival transfer", "Old City heritage walk"],
        ["Dinner"],
        "Jaipur Heritage Haveli",
        "Jaipur",
    ],
    [
        2,
        "Jaipur forts and palaces",
        "Explore Amber Fort, City Palace, Jantar Mantar and local artisan districts.",
        ["Amber Fort", "City Palace", "Jantar Mantar", "Block-printing workshop"],
        ["Breakfast"],
        "Jaipur Heritage Haveli",
        "Jaipur",
    ],
    [
        3,
        "Jaipur to Pushkar",
        "Travel to Pushkar with a guided lake and temple walk.",
        ["Private road transfer", "Pushkar Lake walk", "Brahma Temple"],
        ["Breakfast"],
        "Pushkar Lakeside Retreat",
        "Pushkar",
    ],
    [
        4,
        "Pushkar to Jodhpur",
        "Continue to the Blue City and enjoy a rooftop sunset experience.",
        ["Private road transfer", "Blue City walk", "Rooftop sunset"],
        ["Breakfast"],
        "Jodhpur Blue City Palace",
        "Jodhpur",
    ],
    [
        5,
        "Mehrangarh and Bishnoi country",
        "Tour Mehrangarh Fort and optionally meet artisan communities outside Jodhpur.",
        ["Mehrangarh Fort", "Jaswant Thada", "Bishnoi village visit"],
        ["Breakfast"],
        "Jodhpur Blue City Palace",
        "Jodhpur",
    ],
    [
        6,
        "Jodhpur to Udaipur",
        "Drive through the Aravallis via the marble Jain temples of Ranakpur.",
        ["Ranakpur Jain Temple", "Scenic Aravalli drive"],
        ["Breakfast"],
        "Udaipur Lake Palace Retreat",
        "Udaipur",
    ],
    [
        7,
        "Udaipur lakes and palaces",
        "Discover City Palace, the old quarter and Lake Pichola by boat.",
        ["City Palace", "Old City walk", "Lake Pichola boat ride"],
        ["Breakfast"],
        "Udaipur Lake Palace Retreat",
        "Udaipur",
    ],
    [
        8,
        "Departure from Udaipur",
        "Breakfast and private transfer for your onward journey.",
        ["Private departure transfer"],
        ["Breakfast"],
        "",
        "Udaipur",
    ],
].map(([day, title, summary, activities, meals, accommodation, location]) => ({
    day,
    title,
    summary,
    activities,
    structuredActivities: activities.map((name) => ({
        name,
        description: summary,
        duration: "Flexible",
        price: 0,
        currency: INR,
        included: true,
        bookable: false,
    })),
    meals,
    accommodation,
    location,
    notes: "Timing may be adjusted to the traveller's preferred pace.",
}));

await mongoose.connect(config.MONGO_URI);

try {
    const masters = await User.find({ role: "admin", adminLevel: "master" })
        .select("_id name email accountStatus adminApprovalStatus")
        .lean();
    if (masters.length !== 1)
        throw new Error(`Expected exactly one master admin, found ${masters.length}`);
    const [master] = masters;
    if (master.accountStatus !== "active" || master.adminApprovalStatus !== "approved") {
        throw new Error(
            "The master admin must be active and approved before seeding a published tour",
        );
    }

    const now = new Date();
    const existing = await Tour.findOne({ slug: TOUR_SLUG });
    const tour = existing || new Tour({ slug: TOUR_SLUG });
    tour.set({
        agencyId: null,
        createdBy: master._id,
        productKey: "trevista",
        visibility: "public",
        archivedAt: null,
        slug: TOUR_SLUG,
        title: "Rajasthan Royal Custom Signature Journey",
        shortDescription:
            "An eight-day Rajasthan journey with three packages, room-level hotel choices and a fully customisable quote.",
        agentRef: "",
        city: { from: "Delhi", to: "Udaipur" },
        address: {
            line1: "City Palace Road",
            line2: "Old City",
            city: "Udaipur",
            state: "Rajasthan",
            zip: "313001",
            country: "India",
        },
        distance: 1280,
        period: { days: 8, nights: 7 },
        startDate: null,
        endDate: null,
        photo: photos.hero,
        photos: [
            photos.hero,
            ...photos.jaipur,
            ...photos.pushkar,
            ...photos.jodhpur,
            ...photos.udaipur,
        ],
        desc: "Travel through Jaipur, Pushkar, Jodhpur and Udaipur on a private, customisable Rajasthan circuit. Choose an Essential, Signature or Royal package, then tailor hotel rooms, activities, meals, transfers and flight assistance. Every displayed amount is calculated by the backend from confirmed supplier costs, the platform fee and GST before an agent prepares the final quote.",
        price: { min: 0, max: 0, currency: INR, isFinal: false, source: "component_calculation" },
        commercial,
        seasonalPricing: [],
        itinerary,
        highlights: [
            {
                title: "Four royal cities",
                short: "Jaipur, Pushkar, Jodhpur and Udaipur in one private circuit.",
                icon: "map",
                order: 1,
            },
            {
                title: "Room-level choice",
                short: "Standard, deluxe and suite categories mapped to every package.",
                icon: "hotel",
                order: 2,
            },
            {
                title: "Private transport",
                short: "Air-conditioned intercity vehicle throughout the journey.",
                icon: "car",
                order: 3,
            },
            {
                title: "Custom pace",
                short: "Dates, interests, dining and activities can be tailored before quoting.",
                icon: "sparkles",
                order: 4,
            },
        ],
        includedStays: hotelOptions
            .filter((item) =>
                item.rooms.some((itemRoom) => itemRoom.packageKeys.includes("essential")),
            )
            .map((item) => ({
                nights: item.nights,
                location: item.location,
                propertyName: item.propertyName,
                propertyClass: item.propertyClass,
                roomType: item.rooms[0].name,
                meals: item.rooms[0].meals,
                description: `${item.rooms[0].name} is included in the Essential package; higher room categories are available.`,
                photos: item.photos,
                amenities: item.amenities,
                tier: "base",
                pricing: {
                    unit: "PER_ROOM_PER_NIGHT",
                    amountMinor: item.rooms[0].pricing.amountMinor,
                    currency: INR,
                },
            })),
        hotelOptions,
        cancellation: {
            policy: "Refunds depend on the number of days remaining before the confirmed departure date.",
            freeCancellationUntil: "30 days before departure",
            refundPercent: 100,
            depositRequired: true,
            depositPercent: 25,
            depositNote: "A 25% deposit confirms supplier reservations after quote acceptance.",
            note: "Non-refundable supplier charges are clearly disclosed in the final quote.",
            tiers: [
                {
                    label: "Free cancellation",
                    daysBefore: 30,
                    refundPercent: 100,
                    description: "Full refund before supplier commitments become non-refundable.",
                },
                {
                    label: "Partial refund",
                    daysBefore: 15,
                    refundPercent: 60,
                    description: "Sixty percent refund from 15 to 29 days before departure.",
                },
                {
                    label: "Late cancellation",
                    daysBefore: 7,
                    refundPercent: 25,
                    description: "Twenty-five percent refund from 7 to 14 days before departure.",
                },
                {
                    label: "Non-refundable",
                    daysBefore: 0,
                    refundPercent: 0,
                    description: "No refund within seven days of departure.",
                },
            ],
        },
        extras: [
            {
                title: "Jaipur hot-air balloon",
                description: "Shared sunrise balloon flight, weather permitting.",
                price: 12500,
                currency: INR,
                priceLabel: "₹12,500 per person",
                icon: "balloon",
                category: "activity",
                included: false,
                active: true,
                pricing: { unit: "PER_PERSON", amountMinor: money(12500), currency: INR },
            },
            {
                title: "Private cooking class",
                description: "Market visit and private Rajasthani cooking session.",
                price: 2600,
                currency: INR,
                priceLabel: "₹2,600 per person",
                icon: "meal",
                category: "meal",
                included: false,
                active: true,
                pricing: { unit: "PER_PERSON", amountMinor: money(2600), currency: INR },
            },
            {
                title: "Travel insurance",
                description: "Domestic travel protection for the tour dates.",
                price: 1400,
                currency: INR,
                priceLabel: "₹1,400 per person",
                icon: "shield",
                category: "insurance",
                included: false,
                active: true,
                pricing: { unit: "PER_PERSON", amountMinor: money(1400), currency: INR },
            },
            {
                title: "Private airport transfers",
                description: "Pickup and drop in a private air-conditioned vehicle.",
                price: 3800,
                currency: INR,
                priceLabel: "₹3,800 per booking",
                icon: "car",
                category: "transfer",
                included: false,
                active: true,
                pricing: { unit: "PER_BOOKING", amountMinor: money(3800), currency: INR },
            },
        ],
        availability: { totalSeats: null, seatsAvailable: null },
        packageType: "custom",
        departures: [],
        flexibleConfig: {
            earliestDeparture: null,
            latestReturn: null,
            blackoutDates: [],
            pricingModel: "on_request",
            minAdvanceBookingDays: 7,
            maxAdvanceBookingDays: 365,
        },
        customConfig: {
            responseTimeframeHours: 24,
            requireDates: true,
            requireGroupSize: true,
            allowAgentDraft: true,
            allowCustomerCustomization: true,
            questionnaireFields: [
                "budget",
                "preferredPackage",
                "hotelRoomPreference",
                "interests",
                "travelPace",
                "mealPreferences",
                "dietaryRequirements",
                "accessibilityNeeds",
                "specialOccasion",
                "flightAssistance",
                "additionalNotes",
            ],
        },
        flights: {
            included: false,
            inventoryManaged: false,
            pricePerPerson: 0,
            currency: INR,
            departureCity: "Delhi",
            arrivalCity: "Jaipur",
            airline: "",
            notes: "Flights are excluded and can be sourced in the personalised quote.",
        },
        meetingPoint: "Jaipur Airport, Jaipur Railway Station or an agreed Jaipur hotel",
        inclusions: [
            "Seven nights in the room category mapped to the selected package",
            "Private intercity transport",
            "Daily meals shown in the selected package",
            "Package-specific sightseeing and entry fees",
            "Local guide services",
            "24-hour trip assistance",
            "All pricing shown in the accepted backend quote",
        ],
        exclusions: [
            "Airfare unless added to the quote",
            "Visa and passport costs",
            "Personal expenses",
            "Optional experiences not selected",
            "Camera fees where charged locally",
            "Anything not listed in the accepted quote",
        ],
        languages: ["English", "Hindi", "French on request"],
        cancellationPolicy:
            "Free cancellation until 30 days before the confirmed departure; tiered refunds apply after that date.",
        minAge: 2,
        maxAge: 85,
        maxGroupSize: 20,
        reviews: [
            {
                name: "Ananya Mehta",
                rating: 5,
                comment:
                    "The room choices were clear and the private itinerary made travelling with family easy.",
            },
            {
                name: "Rohan Kapoor",
                rating: 4.8,
                comment:
                    "Excellent local guides, responsive support and a well-paced Rajasthan route.",
            },
        ],
        featured: true,
        trending: true,
        group: { min: 1, max: 20 },
        destinations: [
            {
                destinationId: "jaipur",
                name: "Jaipur",
                cityId: "jaipur",
                cityName: "Jaipur",
                countryId: "india",
                countryName: "India",
                sortOrder: 0,
            },
            {
                destinationId: "pushkar",
                name: "Pushkar",
                cityId: "pushkar",
                cityName: "Pushkar",
                countryId: "india",
                countryName: "India",
                sortOrder: 1,
            },
            {
                destinationId: "jodhpur",
                name: "Jodhpur",
                cityId: "jodhpur",
                cityName: "Jodhpur",
                countryId: "india",
                countryName: "India",
                sortOrder: 2,
            },
            {
                destinationId: "udaipur",
                name: "Udaipur",
                cityId: "udaipur",
                cityName: "Udaipur",
                countryId: "india",
                countryName: "India",
                sortOrder: 3,
            },
        ],
        metrics: { views: 1248, bookings: 37, wishlists: 186, popularityScore: 92, trendScore: 88 },
        ownerAgent: null,
        agentTour: false,
        agencyRef: "",
        partnerAgencyRef: "",
        inventorySource: "platform",
        providerName: "TravelsTREM",
        isPublished: true,
        status: "published",
        builderProcess: null,
        tremVerified: true,
        tremVerifiedBy: master._id,
        tremVerifiedAt: now,
    });

    const summary = deriveTourCommercialSummary(tour.toObject({ depopulate: true }));
    tour.set({
        "commercial.derived": {
            minAmountMinor: summary.minMinor,
            maxAmountMinor: summary.maxMinor,
            calculatedAt: now,
            displayMode: "STARTING_FROM",
            packages: summary.packages,
        },
        price: {
            min: Math.round(summary.minMinor / 100),
            max: Math.round(summary.maxMinor / 100),
            currency: INR,
            isFinal: false,
            source: "component_calculation",
        },
    });

    await tour.save();

    console.log(
        JSON.stringify(
            {
                database: mongoose.connection.name,
                operation: existing ? "updated" : "created",
                masterAdmin: { id: String(master._id), name: master.name, email: master.email },
                tour: {
                    id: String(tour._id),
                    slug: tour.slug,
                    title: tour.title,
                    status: tour.status,
                    packageType: tour.packageType,
                    customerCustomisation: tour.customConfig.allowCustomerCustomization,
                    packages: tour.commercial.packages.map(({ packageKey, name }) => ({
                        packageKey,
                        name,
                    })),
                    components: tour.commercial.components.length,
                    hotels: tour.hotelOptions.length,
                    rooms: tour.hotelOptions.reduce((total, item) => total + item.rooms.length, 0),
                    price: tour.price,
                },
            },
            null,
            2,
        ),
    );
} finally {
    await mongoose.disconnect();
}
