(function configureTravelsTremWebsite(global) {
  const TRAVELSTREM_WEBSITE = {
    navigation: {
      home: {
        home: "#top",
        caption: "Travel technology, engineered end to end.",
        menuLabel: "Explore the solution",
        cta: "Book a demo",
        ctaKey: "bookDemo",
        ctaHref: "#book-demo",
        links: [
          { href: "#products", label: "Products" },
          { href: "#travellers", label: "Solutions" },
          { href: "#quality", label: "Engineering" },
          { href: "#journey", label: "How it works" },
          { href: "#book-demo", label: "Book a demo" },
        ],
      },
      partnership: {
        home: "index.html",
        caption: "A complete travel SaaS engineering solution.",
        menuLabel: "Explore the platform",
        cta: "Book a demo",
        ctaKey: "bookDemo",
        ctaHref: "#book-demo",
        links: [
          { href: "#partner-trem", label: "Platform" },
          { href: "#capabilities", label: "Products" },
          { href: "#workflow", label: "Engineering" },
          { href: "#pricing", label: "Engagement models" },
          { href: "#book-demo", label: "Book a demo" },
        ],
      },
    },
    analytics: {
      enabled: true,
      measurementId: "G-RP0Z50DM4P",
      hosts: ["travelstrem.com", "www.travelstrem.com"],
    },
    ads: {
      enabled: true,
      publisherId: "ca-pub-2541753556383634",
      hosts: ["travelstrem.com", "www.travelstrem.com"],
      label: "Advertisement",
      placements: {
        home: [
          { name: "home-discovery", after: "src/sections/home/travellers.html", slot: "" },
          { name: "home-journey", after: "src/sections/home/quality.html", slot: "" },
        ],
        partnership: [
          { name: "partner-workflow", after: "src/sections/partnership/workflow.html", slot: "" },
        ],
      },
    },
    brand: {
      name: "TravelsTREM",
      partnerName: "PartnerTREM",
      operator: "Shree Air Tours & Travels",
    },
    contact: {
      email: "akshat.goyal@travelstrem.com",
      phoneHref: "+919602225763",
      phoneLabel: "+91 90576 35580",
      locationLabel: "Shree Air Tours and Travels, Jaipur",
    },
    demo: {
      email: "akshat.goyal@travelstrem.com",
      eyebrow: "Product walkthrough",
      title: "Book your TravelsTREM demo",
      copy: "Tell us what you want to build or adopt. Choose a convenient date and time, and we will prepare the conversation around your needs.",
      submit: "Prepare demo request",
    },
    leadership: {
      chairperson: { name: "Mrs. Nisha Goyal", role: "Chairperson" },
      founder: { name: "Mr. Shreekant Goyal", role: "Founder &amp; Managing Director" },
      executive: { name: "Mr. Akshat Goyal", role: "CEO &amp; Executive Director" },
    },
    pricing: {
      start: { name: "Complete SaaS", monthlyPrice: "Custom" },
      growth: { name: "White-labelled Platform", monthlyPrice: "Custom" },
      signature: { name: "Individual Products", monthlyPrice: "Custom" },
    },
    links: {
      main: { href: "#top" },
      home: { href: "#top" },
      about: { href: "#about" },
      ecosystem: { href: "#ecosystem" },
      agency: { href: "#agency" },
      people: { href: "#people" },
      partners: { href: "#partners" },
      contact: { href: "#contact" },
      bookDemo: { href: "#book-demo" },
      partnershipDetails: { href: "#book-demo" },
      partnership: {
        href: "#book-demo",
      },
      trevio: {
        href: "#book-demo",
      },
      trevista: {
        href: "#book-demo",
      },
      trehub: {
        href: "#book-demo",
      },
      hub: {
        href: "#book-demo",
      },
      bookingEngine: {
        href: "#book-demo",
      },
      partnerApplication: {
        href: "#book-demo",
      },
      partnerDemo: {
        href: "#book-demo",
      },
      email: { href: "mailto:akshat.goyal@travelstrem.com" },
      phone: { href: "tel:+919602225763" },
      location: {
        href: "https://maps.app.goo.gl/ebvDhsdzAe27XRSn7",
        external: true,
      },
    },
    content: {
      pages_home_end: {
        strong1: "TravelsTREM",
        small1: "Travel technology, engineered end to end.",
        p1: "A complete travel engineering solution available as a full SaaS platform, a white-labelled product, or individual production-ready modules.",
        h31: "Explore",
        a1: "Solution models",
        a2: "Products",
        a3: "Book a product demo",
        a4: "Delivery journey",
        a5: "Engineering foundation",
        a6: "Book a platform demo",
        h32: "Contact",
        a7: "Book a demo",
        span1: "Trevio · Trevista · TreHub · Dashboard · Partner TREM · AdminTREM · Booking Engine",
      },
      pages_home_start: {
        title1: "TravelsTREM | Complete Travel SaaS Engineering Solution",
        strong1: "TravelsTREM",
        small1: "Complete travel technology suite",
        a1: "Solution models",
        a2: "Products",
        a3: "Book a demo",
        a4: "Delivery journey",
        a5: "Engineering foundation",
        a6: "Platform suite",
        a7: "Book a demo",
        a8: "Solution models",
        a9: "Products",
        a10: "Book a demo",
        a11: "Delivery journey",
        a12: "Engineering foundation",
        a13: "Platform suite",
        a14: "Book a demo",
      },
      pages_partnership_end: {
        strong1: "TravelsTREM",
        small1: "Travel is personal. The platform should be too.",
        p1: "A production-ready travel SaaS engineering solution available as a complete platform, a white-labelled deployment, or individual products.",
        h31: "Explore",
        a1: "Platform",
        a2: "Book a demo",
        a3: "Partner TREM + AdminTREM",
        a4: "Leadership",
        h32: "Contact",
        a5: "Book a demo",
        span1: "Complete SaaS · White label · Individual products",
      },
      pages_partnership_start: {
        title1: "TravelsTREM | Travel SaaS Products and White-label Platform",
        strong1: "Partner TREM + AdminTREM",
        small1: "Agency operations and platform administration.",
        a1: "Capabilities",
        a2: "Workflow",
        a3: "Distribution",
        a4: "Pricing",
        a5: "Book a demo →",
        a6: "Capabilities",
        a7: "Workflow",
        a8: "Distribution",
        a9: "Pricing",
        a10: "Book a product demo",
        a11: "Book a demo →",
      },
      sections_home_about: {
        strong1: "20+ years",
        span1: "Travel-industry experience",
        span2: "Shree Air Tours &amp; Travels",
        div1: "SERVICE → OPERATIONS → SUPPLIERS → PARTNER COORDINATION",
        h31: "Experience behind every TravelsTREM journey.",
        p1: "Shree Air Tours &amp; Travels brings more than two decades of practical travel knowledge to the platform—keeping technology grounded in what travellers need and what agencies must deliver before, during and after every journey.",
        div2: "NG",
        p2: "Guides the organisation’s service culture, stewardship and long-term direction.",
        div3: "SG",
        p3: "Leads Shree Air Tours &amp; Travels, its travel relationships and agency operations with more than two decades of industry experience.",
        div4: "AG",
        p4: "Leads the TravelsTREM product and technology vision across traveller and partner workflows.",
      },
      sections_home_contact: {
        span1: "Complete platform",
        h31: "See the entire TravelsTREM SaaS in one guided demo.",
        p1: "Review the customer products, agency operations, booking engine, dashboard and shared engineering foundation as one connected solution.",
        a1: "Book a complete-platform demo",
        span2: "Focused product",
        h32: "Explore only the products your business needs.",
        p2: "Choose Trevio, Trevista, TreHub, Dashboard, Partner TREM, AdminTREM or the Booking Engine and we will tailor the walkthrough to that scope.",
        a2: "Book a product demo",
      },
      sections_home_hero: {
        span1: "A complete travel SaaS engineering solution",
        h11: "Build your travel business on",
        span2: "TravelsTREM",
        p1: "Adopt the complete SaaS platform, launch it under your own white label, or choose individual products—each backed by a production-ready engineering system.",
        a1: "Book a demo",
        a2: "Book a tailored demo",
        small1: "TravelsTREM · Product ecosystem preview",
        span3: "T",
        span4: "Journey connected",
        span5: "Overview",
        span6: "Discover",
        span7: "Enquiries",
        span8: "Bookings",
        span9: "Support",
        small2: "One connected engineering platform",
        h31: "Everything needed to operate and scale.",
        strong1: "04",
        span10: "Saved journeys",
        strong2: "02",
        span11: "Active enquiries",
        strong3: "01",
        span12: "Upcoming trip",
        strong4: "Royal Rajasthan Heritage Circuit",
        span13: "Quote ready",
        strong5: "Varanasi Spiritual Discovery",
        span14: "Agent assigned",
        strong6: "Meghalaya Waterfalls",
        span15: "Saved",
        b1: "Built as a complete product system",
        span16:
          "Applications, engines, design system, documentation, frameworks and reusable packages—ready to demonstrate.",
      },
      sections_home_journey: {
        span1: "Your product journey",
        h21: "From first demo to a solution shaped around your business.",
        p1: "A focused evaluation path helps you choose the right products, ownership model and rollout scope.",
        div1: "01",
        h31: "Share your needs",
        p2: "Tell us about your travel business, users, workflows and current technology.",
        div2: "02",
        h32: "Book a demo",
        p3: "Choose a date, time and the products you want to evaluate.",
        div3: "03",
        h33: "Map the solution",
        p4: "Review the complete SaaS, white-label route or individual product fit.",
        div4: "04",
        h34: "Review architecture",
        p5: "Walk through products, shared engines, design system, frameworks and packages.",
        div5: "05",
        h35: "Define scope",
        p6: "Select the ownership, branding, products and implementation plan.",
        div6: "06",
        h36: "Launch",
        p7: "Move forward with a production-ready foundation and an agreed delivery roadmap.",
      },
      sections_home_marquee: {
        span1: "Complete travel SaaS",
        span2: "White-labelled deployment",
        span3: "Individual products",
        span4: "Booking Engine",
        span5: "Finance Engine",
        span6: "Process Engine",
        span7: "Form Engine",
        span8: "Design system &amp; Storybook",
        span9: "Complete travel SaaS",
        span10: "White-labelled deployment",
        span11: "Individual products",
        span12: "Booking Engine",
        span13: "Finance Engine",
        span14: "Process Engine",
        span15: "Form Engine",
        span16: "Design system &amp; Storybook",
      },
      "sections_home_partner-trem": {
        span1: "Partner TREM + AdminTREM",
        h21: "Agency operations and platform administration, connected.",
        p1: "Partner TREM gives agencies the workspace to manage daily travel operations. AdminTREM gives the platform owner central control over partners, teams, products, workflows and ecosystem performance.",
        i1: "1",
        strong1: "Partner TREM · Agency operations",
        span2: "Manage agents, customers, tours, enquiries, quotes, bookings and fulfilment.",
        i2: "2",
        strong2: "AdminTREM · Platform governance",
        span3: "Control partner onboarding, access, products, workflows and system-wide administration.",
        i3: "3",
        strong3: "One connected operating model",
        span4: "Give agencies focused workspaces while the platform team retains oversight and control.",
        a1: "Book a combined demo",
        a2: "Explore both products",
        div1: "Partner TREM + AdminTREM · Connected operations",
        span5: "T",
        span6: "Agency + admin workspace",
        span7: "Overview",
        span8: "Tours",
        span9: "Enquiries",
        span10: "Customers",
        small1: "Connected operating overview",
        h31: "Agency execution. Platform oversight.",
        strong4: "12",
        span11: "Active tours",
        strong5: "08",
        span12: "Open enquiries",
        strong6: "24",
        span13: "Customers",
        strong7: "Royal Rajasthan enquiry",
        span14: "Quote ready",
        strong8: "Varanasi booking",
        span15: "Confirmed",
        strong9: "Meghalaya tour",
        span16: "Published",
        strong10: "Partner TREM · Agency &amp; team",
        span17: "Role-based daily workspace for agency administrators and travel agents.",
        strong11: "Partner TREM · Sales &amp; operations",
        span18: "Manage tours, customers, enquiries, quotes, bookings and fulfilment.",
        strong12: "AdminTREM · Platform control",
        span19: "Govern partners, access, products, workflows and platform configuration.",
        strong13: "AdminTREM · Oversight",
        span20: "Monitor ecosystem activity, operational health, approvals and reporting.",
        strong14: "Shared engines",
        span21: "Use common finance, process and form foundations across both products.",
        strong15: "Connected accountability",
        span22: "Keep agency ownership and central platform governance clearly separated.",
      },
      "sections_home_platform-preview": {
        span1: "See the platform",
        h21: "The experience continues after you find the tour.",
        p1: "Switch between the Trevista discovery surface and the TravelsTREM traveller hub. The goal is one continuous experience rather than a collection of disconnected pages.",
        button1: "Manage your journey",
        button2: "Tour listing",
        button3: "Tour details",
        button4: "Tour booking",
        span2: "TravelsTREM · Actual product interfaces",
        div1: "Home &nbsp;›&nbsp; My Bookings",
        small1: "TOUR SUPPORT",
        h31: "My bookings &amp; enquiries",
        p2: "Track every request you have sent and any booking confirmed for your account.",
        span3: "6 total",
        h41: "All records &nbsp;⑥",
        p3: "Search your enquiries and confirmed bookings.",
        span4: "Search by reference, tour or contact",
        span5: "All records",
        span6: "Newest",
        span7: "REFERENCE",
        span8: "TOUR OR SERVICE",
        span9: "TYPE",
        span10: "SPECIALIST",
        span11: "TRAVELLERS",
        span12: "TRAVEL DATES",
        span13: "STATUS",
        span14: "CREATED",
        span15: "ENQ-0BBEF6",
        b1: "Varanasi Spiritual Discovery",
        span16: "Trevista",
        span17: "Enquiry",
        span18: "Tanshu Goyal",
        span19: "2",
        span20: "19–26 Sept 2026",
        span21: "● New",
        span22: "26 Aug 2026",
        span23: "ENQ-B10173",
        b2: "Custom tour enquiry",
        span24: "Trevista",
        span25: "Enquiry",
        span26: "Akshat Goyal",
        span27: "1",
        span28: "Flexible",
        span29: "● New",
        span30: "26 Aug 2026",
        span31: "ENQ-42E4B3",
        b3: "Delhi to Leh Himalayan Road Expedition",
        span32: "Trevista",
        span33: "Enquiry",
        span34: "Shreekant Goyal",
        span35: "2",
        span36: "19–26 Sept 2026",
        span37: "● New",
        span38: "24 Aug 2026",
        span39: "ENQ-9D6A98",
        b4: "Royal Rajasthan Heritage Circuit",
        span40: "Trevista",
        span41: "Enquiry",
        span42: "Shreekant Goyal",
        span43: "2",
        span44: "10–15 Oct 2026",
        span45: "● New",
        span46: "24 Aug 2026",
        div2: "Find your perfect adventure",
        span47: "All tours",
        span48: "Domestic",
        span49: "International",
        span50: "Featured",
        span51: "Adventure",
        span52: "Family",
        span53: "Luxury",
        div3: "Can't find a tour that fits?",
        b5: "Create a custom journey.",
        span54: "⌁ &nbsp; Filters",
        span55: "⌕ &nbsp; Search by tour, destination, or experience…",
        b6: "10 tours",
        div4: "Showing&nbsp; 8 of 10",
        div5: "◉ &nbsp; You're signed in. Save favourites and manage your Trevista bookings from your dashboard.",
        span56: "☆ Featured",
        small2: "SHILLONG TO CHERRAPUNJI",
        h42: "Meghalaya Waterfalls and Living Roots",
        div6: "☆ 0.0 · Cherrapunji, India · 8 days",
        span57: "Standard",
        b7: "₹24,992",
        span58: "Premium",
        b8: "₹36,536",
        span59: "Advance",
        b9: "₹52,844",
        span60: "Explore this Tour",
        span61: "☆ Featured",
        small3: "VARANASI TO SARNATH",
        h43: "Varanasi Spiritual Discovery",
        div7: "☆ 0.0 · Sarnath, India · 8 days",
        span62: "Standard",
        b10: "₹24,992",
        span63: "Premium",
        b11: "₹36,536",
        span64: "Advance",
        b12: "₹52,844",
        span65: "Explore this Tour",
        span66: "☆ Featured",
        small4: "PANAJI TO SOUTH GOA",
        h44: "Goa Coast and Heritage Getaway",
        div8: "☆ 0.0 · South Goa, India · 8 days",
        span67: "Standard",
        b13: "₹24,992",
        span68: "Premium",
        b14: "₹36,536",
        span69: "Advance",
        b15: "₹52,844",
        span70: "Explore this Tour",
        span71: "☆ Featured",
        small5: "DELHI TO LEH",
        h45: "Delhi to Leh Himalayan Road Expedition",
        div9: "☆ 0.0 · Leh, India · 8 days",
        span72: "Standard",
        b16: "₹24,992",
        span73: "Premium",
        b17: "₹36,536",
        span74: "Advance",
        b18: "₹52,844",
        span75: "Explore this Tour",
        small6: "Trevista &nbsp;›&nbsp; Tours &nbsp;›&nbsp; Varanasi Spiritual Discovery",
        span76: "⌕ &nbsp; Search tours, bookings, enquiries, support…",
        span77: "Overview",
        span78: "Packages",
        span79: "Itinerary",
        span80: "Inclusions",
        span81: "Hotels &amp; stays",
        span82: "Policies",
        small7: "Route",
        b19: "Varanasi to Sarnath",
        small8: "Duration",
        b20: "8 days · 7 nights",
        small9: "Dates",
        b21: "19 Sept to 26 Sept",
        small10: "Seats",
        b22: "18 available",
        b23: "Operated by",
        br1: "Shree Air tours &amp; travels",
        b24: "Uploaded by agent",
        br2: "Tanshu Goyal",
        h46: "✦ &nbsp; Highlights",
        b25: "Delhi to Leh Overland Journey",
        span83: "Cross the Himalayas through Manali and Jispa.",
        b26: "Atal Tunnel &amp; Lahaul Valley",
        span84: "Experience the changing landscapes beyond Manali.",
        b27: "High Himalayan Passes",
        span85: "Travel through Baralacha La and Tanglang La.",
        b28: "Leh &amp; Sham Valley",
        span86: "Explore Leh Palace and Magnetic Hill.",
        b29: "Three Package Choices",
        span87: "Choose the travel style that suits you.",
        h32: "Tour packages",
        small11: "STANDARD",
        b30: "₹24,992",
        h47: "Essential journey",
        p4: "Comfortable stays and shared travel for a great-value experience.",
        li1: "Standard accommodation",
        li2: "Shared road transport",
        li3: "Essential sightseeing",
        button5: "Choose this plan",
        small12: "PREMIUM · RECOMMENDED",
        b31: "₹36,536",
        h48: "Premium journey",
        p5: "Upgraded stays, premium transport and expanded sightseeing.",
        li4: "Premium accommodation",
        li5: "Premium road transport",
        li6: "Airport drop included",
        button6: "Selected",
        small13: "ADVANCE",
        b32: "₹52,844",
        h49: "Signature journey",
        p6: "Private premium travel with elevated stays and personal service.",
        li7: "Signature accommodation",
        li8: "Private SUV transport",
        li9: "Private sightseeing",
        button7: "Choose this plan",
        small14: "YOUR JOURNEY",
        h33: "Andaman Island Discovery",
        p7: "Booking reference ENQ-A32BFA · Signature package",
        span88: "Quote received",
        h410: "Your booking journey",
        b33: "Enquiry completed",
        span89: "Your travel requirements were shared with the partner.",
        b34: "Review your quotation",
        span90: "Download, request a change or accept the prepared quote.",
        b35: "Add traveller details",
        span91: "Complete traveller information after accepting the quote.",
        b36: "Travel updates",
        span92: "Follow documents, tickets and live booking progress.",
        h411: "Your personalised quotation",
        small15: "PREPARED FOR YOUR REQUEST",
        strong1: "Signature island journey for five travellers",
        span93: "Journey prepared by your travel partner",
        b37: "₹3,28,552",
        span94: "TravelsTREM service fee",
        b38: "₹3,286",
        span95: "Applicable tax",
        b39: "₹591",
        span96: "Total quotation",
        b40: "₹3,32,429",
        span97: "Download PDF",
        span98: "Request changes",
        span99: "Accept quote",
      },
      sections_home_products: {
        span1: "Our Products",
        h21: "Seven products. One travel technology ecosystem.",
        p1: "Every product is production-ready and can be demonstrated as part of the complete TravelsTREM SaaS, a white-labelled platform, or an individual solution.",
        span2: "Community travel",
        h31: "Trevio",
        p2: "Community trips, adventures, treks, expeditions and travel communities with shared departures.",
        li1: "Fixed departures with live availability",
        li2: "Trip captains and travel communities",
        span3: "View details",
        span4: "Tours & holidays",
        h32: "Trevista",
        p3: "Curated holiday packages with detailed itineraries, personalised quotes and connected bookings.",
        li3: "Curated domestic &amp; international tours",
        li4: "Personalised enquiry and quote journey",
        span5: "View details",
        span6: "Flights & hotels",
        h33: "TreHub",
        p4: "Flight and hotel search connected to your journey, with fares, timings and stay options in one comparison view.",
        li5: "Flight options and hotel stays together",
        li6: "Compare, shortlist and attach to a trip",
        span7: "View details",
        span8: "Connected",
        h34: "Dashboard",
        p5: "One account that links discovery, enquiries, quotes, bookings, documents and support across products.",
        li7: "Single account across every product",
        li8: "Bookings, documents and support in one place",
        span9: "View details",
        span10: "For agencies",
        h35: "Partner TREM",
        p6: "A role-based workspace where agencies run tours, enquiries, customers and bookings together.",
        li9: "Create, organise and publish tours",
        li10: "Enquiries, quotes and bookings management",
        span11: "View details",
        span12: "Transaction infrastructure",
        h36: "Booking Engine",
        p7: "A connected booking lifecycle for quotes, travellers, payments, documents, fulfilment and post-booking operations.",
        li11: "Configurable booking and payment journey",
        li12: "Documents, status and fulfilment together",
        span13: "View details",
        span14: "Admin dashboard",
        h37: "AdminTREM",
        p8: "An administration dashboard for platform-wide partner governance, access control, product configuration, oversight and reporting.",
        li13: "Partner, team and access administration",
        li14: "Platform controls, approvals and reporting",
        span15: "View details",
        span16: "Upcoming plans",
        h38: "The next TravelsTREM products",
        p9: "Two focused products are planned to extend internal operations and traveller services.",
        h39: "Support Dashboard",
        p10: "A central help-and-support workspace for requests, escalations, service operations and internal team management.",
        li15: "Help desk, ticket ownership and escalation",
        li16: "Internal teams, queues and operational visibility",
        h310: "TreCARE",
        p11: "A traveller-services product for visa and passport assistance, forex, transfers, insurance and related travel essentials.",
        li17: "Visa and passport assistance",
        li18: "Forex, transfers, insurance and additional services",
        a1: "Book a product demo",
      },
      sections_home_promises: {
        small1: "01 · Complete",
        strong1: "Full SaaS product ownership",
        small2: "02 · Branded",
        strong2: "White-labelled for your business",
        small3: "03 · Modular",
        strong3: "Choose individual products",
        small4: "04 · Engineered",
        strong4: "Shared systems, frameworks &amp; packages",
      },
      sections_home_quality: {
        span1: "Engineering foundation",
        h21: "The product includes the systems teams need to build, operate and extend it.",
        p1: "TravelsTREM is delivered with a coherent engineering foundation—not only customer-facing screens.",
        span2: "01 / UI FOUNDATION",
        h31: "Storybook &amp; design system",
        p2: "Reusable visual standards, documented interface components and shared interaction patterns across products.",
        span3: "02 / KNOWLEDGE",
        h32: "Documentation &amp; frameworks",
        p3: "Product documentation and reusable application frameworks make implementation and extension easier to govern.",
        span4: "03 / CORE ENGINES",
        h33: "Finance, Process &amp; Form Engines",
        p4: "Shared engines support commercial calculations, workflow orchestration and structured form experiences.",
        span5: "04 / REUSE",
        h34: "Shared packages",
        p5: "Reusable packages keep contracts, utilities and platform capabilities consistent across the product family.",
      },
      sections_shared_builders: {
        eyebrow: "Process Engine + Form Engine",
        title: "Guided builders turn complex travel operations into clear, saved workflows.",
        copy: "Each builder uses shared process orchestration, validation and structured forms so teams always know the current step, required information and next action.",
        agencyLabel: "Agency Builder",
        agencyTitle: "Agency partnership activation",
        agencyCopy: "Create and verify an agency through one governed onboarding process.",
        agencyStatus: "Not started",
        agencyStep: "Step 1 of 6",
        agencyHeading: "Business identity",
        agencyDescription: "Tell us who the agency is and how customers know the business.",
        agencySteps: ["Business identity", "Registration &amp; address", "Agency operations", "Primary contact", "Verification", "Review &amp; submit"],
        tourLabel: "Tour Builder",
        tourTitle: "Build a complete travel product",
        tourCopy: "Structure the itinerary, stays, packages, pricing and publishing controls in one flow.",
        tourStatus: "Draft saved",
        tourStep: "Step 2 of 6",
        tourHeading: "Route &amp; itinerary",
        tourDescription: "Define the journey structure once, then connect every package and departure to it.",
        tourSteps: ["Tour basics", "Route &amp; itinerary", "Stays &amp; inclusions", "Packages &amp; pricing", "Departures", "Review &amp; publish"],
        quoteLabel: "Quote Builder",
        quoteTitle: "Compose traveller quotation",
        quoteCopy: "Turn the customer request, selected package and customisations into a controlled commercial document.",
        quoteStatus: "Draft",
        quoteStep: "Step 1 of 5",
        quoteHeading: "Customer request",
        quoteDescription: "Review what the traveller asked for before building the itemised quotation.",
        quoteSteps: ["Customer request", "Included tour", "Changes &amp; customisations", "Itemised quotation", "Review &amp; send"],
      },
      sections_home_travellers: {
        span1: "Choose your solution model",
        h21: "Adopt TravelsTREM in the way that fits your business.",
        p1: "Start with the complete platform, brand it as your own, or add focused products and engines to your current technology landscape.",
        b1: "01",
        h31: "Complete SaaS platform",
        p2: "Adopt the connected customer, partner, booking and operational ecosystem as one product suite.",
        b2: "02",
        h32: "White-labelled platform",
        p3: "Deploy the platform with your identity, positioning and product configuration.",
        b3: "03",
        h33: "Individual products",
        p4: "Choose Trevio, Trevista, TreHub, Dashboard, Partner TREM, AdminTREM or the Booking Engine independently.",
        b4: "04",
        h34: "Shared platform engines",
        p5: "Use the Finance, Process and Form Engines as a consistent foundation across workflows.",
        b5: "05",
        h35: "Design system &amp; Storybook",
        p6: "Keep teams aligned with reusable components, tokens and documented product patterns.",
        b6: "06",
        h36: "Documentation &amp; packages",
        p7: "Extend the system through documented frameworks and reusable packages built for the product family.",
      },
      sections_partnership_agency: {
        span1: "Tailored product demo",
        h21: "See how TravelsTREM fits your product and operating model.",
        p1: "Walk through the complete SaaS, a white-labelled deployment, or a focused combination of products and engineering engines.",
        a1: "Book a complete demo",
        a2: "Book a focused demo",
        strong1: "Agency &amp; agent management",
        span2: "Operate teams with role-aware access and ownership.",
        strong2: "Tour publishing",
        span3: "Create and manage travel inventory that can become customer-facing.",
        strong3: "Quote &amp; booking journey",
        span4: "Move customer requirements through a structured commercial flow.",
        strong4: "Post-payment operations",
        span5: "Track documents, balances and fulfilment beyond checkout.",
      },
      sections_partnership_capabilities: {
        span1: "Partner TREM + AdminTREM",
        h21: "Run agency operations with central platform governance above them.",
        p1: "Partner TREM manages the agency journey. AdminTREM gives the platform owner control over partners, internal teams, access, configuration, approvals and cross-product reporting.",
        strong1: "Partner TREM operations · AdminTREM oversight",
        span2: "Tour creation workspace",
        strong2: "Partner TREM",
        span3: "Tour builder",
        span4: "Inventory",
        span5: "Enquiries",
        span6: "Customers",
        span7: "Reports",
        small1: "Guided workflow",
        h31: "Build a complete travel product.",
        div1: "01 · Basics",
        div2: "02 · Itinerary",
        div3: "03 · Packages",
        div4: "04 · Publish",
        div5: "Tour name",
        strong3: "Royal Rajasthan Heritage Circuit",
        div6: "Product owner",
        strong4: "Shree Air Tours &amp; Travels",
        div7: "Journey type",
        strong5: "Fixed departure",
        div8: "Distribution",
        strong6: "TravelsTREM + Trevista",
        span8: "01 · Agency",
        strong7: "Operations",
        span9: "02 · Team",
        strong8: "People &amp; access",
        span10: "03 · Products",
        strong9: "Tour inventory",
        span11: "04 · Customers",
        strong10: "Enquiries &amp; CRM",
        span12: "05 · Commercial",
        strong11: "Quotes &amp; pricing",
        span13: "06 · Bookings",
        strong12: "Journey fulfilment",
        span14: "07 · Finance",
        strong13: "Payments &amp; records",
        small2: "Agency command centre",
        h32: "Know what needs attention.",
        span15: "Live workspace",
        h41: "Open enquiries",
        strong14: "18",
        p2: "Incoming customer requirements waiting for action.",
        h42: "Quotes in progress",
        strong15: "11",
        p3: "Draft, sent and revised commercial proposals.",
        h43: "Bookings in journey",
        strong16: "9",
        p4: "Confirmed bookings that still need delivery actions.",
        h44: "Published tours",
        strong17: "24",
        p5: "Your marketplace-ready travel inventory.",
        h45: "Priority queue",
        strong18: "Kashmir · 5N/6D",
        span16: "Quote accepted",
        span17: "Collect advance",
        strong19: "Bali · 6N/7D",
        span18: "New enquiry",
        span19: "Assign agent",
        strong20: "Dubai · 4N/5D",
        span20: "Booked",
        span21: "Upload tickets",
        h46: "Workflow health",
        strong21: "One view",
        p6: "Agency admins can see the movement from enquiry to delivery instead of tracking disconnected spreadsheets.",
        small3: "Agency operations",
        h33: "Manage the business and the people responsible for every journey.",
        span22: "Role-based access",
        h47: "Agency workspace",
        strong22: "Shree Air Tours &amp; Travels",
        p7: "Verified agency profile · Active partner",
        h48: "Team overview",
        strong23: "12",
        span23: "Total members",
        strong24: "10",
        span24: "Active accounts",
        strong25: "2",
        span25: "Pending invitations",
        p8: "Invite agents, manage their status and keep workspace ownership clear.",
        h49: "Agency team",
        strong26: "Shreekant Goyal",
        span26: "Partner admin",
        span27: "Active",
        strong27: "Tanshu Goyal",
        span28: "Travel agent",
        span29: "Active",
        strong28: "Operations desk",
        span30: "Support team",
        span31: "Invited",
        h410: "Access controls",
        strong29: "Tour inventory",
        span32: "Enabled",
        strong30: "Enquiries &amp; quotes",
        span33: "Enabled",
        strong31: "Bookings",
        span34: "Role based",
        p9: "Assign product access and operational responsibility by role.",
        small4: "Tour engine",
        h34: "Create once. Manage departures. Publish when ready.",
        span35: "Marketplace connected",
        h411: "Tour",
        strong32: "Kashmir Escape",
        p10: "5N/6D · Srinagar · Gulmarg · Pahalgam",
        h412: "Tour workspace",
        strong33: "Overview &amp; commercial",
        span36: "Complete",
        span37: "Ready",
        strong34: "Day-wise itinerary",
        span38: "6 days",
        span39: "Ready",
        strong35: "Hotels &amp; inclusions",
        span40: "Configured",
        span41: "Ready",
        strong36: "Departures &amp; capacity",
        span42: "3 active",
        span43: "Managed",
        h413: "Distribution principle",
        strong37: "Your operational inventory can become customer-facing inventory.",
        p11: "Approved tours are not trapped inside the partner portal—they can participate in the TravelsTREM marketplace where the agency is enrolled.",
        small5: "Customer workspace",
        h35: "Keep the requirement, conversation and next action together.",
        span44: "Ownership preserved",
        h414: "Enquiry pipeline",
        strong38: "Andaman family",
        span45: "4 travellers",
        span46: "New",
        strong39: "Kashmir honeymoon",
        span47: "2 travellers",
        span48: "Quoted",
        strong40: "Dubai holiday",
        span49: "5 travellers",
        span50: "Follow-up",
        strong41: "Leh adventure",
        span51: "8 travellers",
        span52: "Won",
        h415: "Customer context",
        strong42: "One journey",
        p12: "Requirements, assigned agent, tour reference, quote activity and booking status remain connected.",
        h416: "Designed for action",
        p13: "Instead of treating an enquiry as an isolated form submission, Partner TREM keeps it as the starting point of the customer lifecycle.",
        small6: "Quote engine",
        h36: "Build options around the traveller, not a static PDF.",
        span53: "Pricing controlled",
        h417: "Quote variants",
        strong43: "Standard",
        span54: "Hotels + transfers",
        span55: "₹72,500",
        strong44: "Premium",
        span56: "Upgraded stay + activities",
        span57: "₹89,900",
        strong45: "Advance",
        span58: "Flights + premium services",
        span59: "₹1,08,400",
        h418: "Final customer price",
        span60: "Agent quote",
        strong46: "₹85,000",
        span61: "TravelsTREM charges",
        strong47: "Applied",
        span62: "Taxes",
        strong48: "Calculated",
        span63: "Final payable",
        strong49: "₹89,900",
        p14: "Pricing logic can stay centrally governed instead of being duplicated in every product flow.",
        h419: "Quote lifecycle",
        p15: "Draft → send → customer reviews → revision if required → accept → proceed to payment. The quote remains part of the same customer journey.",
        small7: "Booking operations",
        h37: "A booking is not finished when payment succeeds.",
        span64: "Post-payment journey",
        h420: "Booking lifecycle",
        b1: "1",
        strong50: "Accepted",
        span65: "Chosen quote",
        b2: "2",
        strong51: "Advance paid",
        span66: "Booking secured",
        b3: "3",
        strong52: "Documents",
        span67: "Tickets &amp; passes",
        b4: "4",
        strong53: "Balance",
        span68: "Final settlement",
        b5: "5",
        strong54: "Completed",
        span69: "Journey delivered",
        h421: "Deliverables",
        strong55: "Flight tickets",
        span70: "Uploaded",
        span71: "Visible",
        strong56: "Hotel vouchers",
        span72: "Uploaded",
        span73: "Visible",
        strong57: "Travel insurance",
        span74: "Pending",
        span75: "Action",
        h422: "Customer view",
        strong58: "Everything in one booking.",
        p16: "Documents, payment progress and status can stay visible from the customer's dashboard.",
        small8: "Commercial records",
        h38: "Track collection, balance and booking value without losing context.",
        span76: "Auditable journey",
        h423: "Total booking value",
        strong59: "₹89,900",
        p17: "Final agreed customer amount.",
        h424: "Collected",
        strong60: "₹30,000",
        p18: "Advance payment received.",
        h425: "Balance",
        strong61: "₹59,900",
        p19: "Remaining settlement to collect.",
        h426: "Payment schedule",
        strong62: "Advance",
        span77: "Paid",
        span78: "₹30,000",
        strong63: "Second payment",
        span79: "Upcoming",
        span80: "₹30,000",
        strong64: "Final balance",
        span81: "Before departure",
        span82: "₹29,900",
        h427: "Monthly records",
        strong65: "Booking → payment → report",
        p20: "Operational records can feed agency-level reporting and future invoice summaries.",
      },
      sections_partnership_contact: {
        span1: "Choose your walkthrough",
        h21: "One platform. A demo shaped around your business.",
        p1: "Explore the complete TravelsTREM SaaS, white-label possibilities, or the individual products and engines that matter to your team.",
        a1: "Book a complete-platform demo",
        a2: "Book a focused demo",
      },
      sections_partnership_distribution: {
        span1: "Flexible product ownership",
        h21: "Use the whole platform, your own brand, or only the products you need.",
        p1: "TravelsTREM supports different commercial and technical adoption paths without separating the underlying product quality.",
        span2: "Own",
        h31: "Adopt the complete SaaS product.",
        p2: "Bring customer discovery, agency operations, booking infrastructure, dashboards and shared engineering systems together.",
        span3: "Configure",
        h32: "White label or select individual products.",
        p3: "Shape the experience around your brand or integrate focused products into your existing technology landscape.",
        small1: "Marketplace status",
        strong1: "Kashmir Escape · Published",
        span4: "Trevista",
        span5: "5N/6D",
        span6: "Partner tour",
      },
      sections_partnership_hero: {
        span1: "TravelsTREM · Complete travel product engineering",
        h11: "Adopt the platform.",
        span2: "Make it entirely yours.",
        p1: "TravelsTREM is ready as a complete SaaS product, a white-labelled travel platform, or individual products including Trevio, Trevista, TreHub, Dashboard, Partner TREM, AdminTREM and the Booking Engine.",
        a1: "Book a demo",
        a2: "Book a product walkthrough",
        div1: "TravelsTREM / solution overview",
        div2: "TravelsTREM",
        span3: "Overview",
        span4: "Enquiries",
        span5: "Tours",
        span6: "Quotes",
        span7: "Bookings",
        span8: "Payments",
        span9: "Customers",
        span10: "Reports",
        small1: "Agency workspace",
        strong1: "Good afternoon, Partner",
        span11: "Connected",
        small2: "Open enquiries",
        strong2: "18",
        em1: "Needs attention",
        small3: "Active quotes",
        strong3: "11",
        em2: "Across travellers",
        small4: "Live tours",
        strong4: "24",
        em3: "Marketplace ready",
        div3: "Customer journey",
        span12: "Today",
        div4: "AS",
        strong5: "Andaman family package",
        small5: "Quote revision requested",
        b1: "Quoted",
        div5: "RK",
        strong6: "Kashmir honeymoon",
        small6: "Advance payment received",
        b2: "Booked",
        div6: "NK",
        strong7: "Dubai holiday",
        small7: "Flight add-on pending",
        b3: "Enquiry",
        div7: "Booking activity",
        span13: "30 days",
        strong8: "Quote received ✓",
        small8: "The customer journey can move forward",
        strong9: "Tour published",
        small9: "Now visible in TravelsTREM",
        span14: "Agency team management",
        span15: "Tour management",
        span16: "Customer enquiries",
        span17: "Quote workflows",
        span18: "Booking lifecycle",
        span19: "Payment tracking",
        span20: "Partner marketplace",
        span21: "Role based operations",
        span22: "Agency team management",
        span23: "Tour management",
        span24: "Customer enquiries",
        span25: "Quote workflows",
        span26: "Booking lifecycle",
        span27: "Payment tracking",
        span28: "Partner marketplace",
        span29: "Role based operations",
      },
      sections_partnership_leadership: {
        span1: "The people behind the journey",
        h21: "Travel experience, business leadership and technology working together.",
        div1: "NG",
        p1: "Guides the organisation's culture of personal service, responsible stewardship and long-term direction.",
        div2: "SG",
        p2: "Leads Shree Air Tours &amp; Travels, its travel relationships and agency operations with more than two decades of industry experience.",
        div3: "AG",
        p3: "Leads TravelsTREM's product and technology vision across travellers, products and partner workflows.",
      },
      sections_partnership_platform: {
        span1: "One engineering platform. Multiple product surfaces.",
        h21: "Built for customer experiences and the operations behind them.",
        p1: "Switch perspectives to see how the customer-facing products and operational products share one connected foundation.",
        button1: "Customer products",
        button2: "Partner TREM + AdminTREM",
      },
      sections_partnership_pricing: {
        span1: "Engagement models",
        h21: "Choose how you want to adopt TravelsTREM.",
        p1: "The right commercial and delivery scope is defined around your product strategy, brand and technical environment.",
        span2: "Entire product suite",
        p2: "For businesses that want the complete connected travel SaaS ecosystem.",
        span3: "tailored scope",
        li1: "All customer and operational products",
        li2: "Booking and shared platform engines",
        li3: "Design system, Storybook and documentation",
        li4: "Frameworks and reusable packages",
        a1: "Book a complete demo →",
        span4: "Your brand",
        p3: "For businesses that want TravelsTREM capabilities presented as their own platform.",
        span5: "tailored scope",
        li5: "White-labelled customer experience",
        li6: "Configured product and workflow scope",
        li7: "Shared engineering foundation",
        li8: "Brand and deployment planning",
        li9: "Product walkthrough before scoping",
        a2: "Book a white-label demo →",
        span6: "Focused adoption",
        p4: "For teams that need one product or a selected combination of capabilities.",
        span7: "tailored scope",
        li10: "Trevio, Trevista or TreHub",
        li11: "Dashboard, Partner TREM or AdminTREM",
        li12: "Booking Engine",
        li13: "Finance, Process and Form Engines",
        li14: "Reusable design and platform packages",
        a3: "Book a product demo →",
        p5: "Commercial terms and implementation scope are discussed after the tailored demo.",
      },
      sections_partnership_workflow: {
        span1: "One continuous workflow",
        h21: "From “I’m interested” to “trip completed” without breaking the chain.",
        p1: "Every stage has an owner and every transition carries the context forward.",
        div1: "01",
        h31: "Discover",
        p2: "Traveller finds an eligible tour through a TravelsTREM product.",
        div2: "02",
        h32: "Enquire",
        p3: "Requirements reach the responsible partner and assigned agent.",
        div3: "03",
        h33: "Customise",
        p4: "The agent adapts the package to the traveller's actual requirement.",
        div4: "04",
        h34: "Quote",
        p5: "Variants are priced, shared, revised and accepted inside the journey.",
        div5: "05",
        h35: "Book &amp; pay",
        p6: "Payment secures the booking and creates the post-payment workflow.",
        div6: "06",
        h36: "Deliver",
        p7: "Tickets, vouchers, balances and trip status continue until completion.",
        strong1: "TREM = Tours → Reservations → Experience → Management",
        span2: "The product architecture follows the full operating journey—not just the checkout.",
        a1: "See Partner TREM ↑",
      },
    },
    products: {
      trehub: {
        status: "Flights & hotels",
        name: "TreHub",
        tagline: "Flight and hotel search connected to your journey",
        about:
          "TreHub brings flight and hotel search into the connected TravelsTREM journey. Compare fares, timings and stay options side by side, shortlist what fits, and keep it attached to the same trip so your enquiry and booking never lose context.",
        features: [
          "Flight options by fare, airline and timing",
          "Hotel stays with ratings, amenities and rates",
          "Side-by-side comparison and shortlist",
          "Connected enquiry and booking through TravelsTREM",
        ],
        linkKey: "trehub",
        cta: "Book a TreHub demo",
      },
      trevio: {
        status: "Community travel",
        name: "Trevio",
        tagline: "Community trips, adventures, treks and expeditions",
        about:
          "Trevio brings travellers together around shared departures. It covers community trips, treks, expeditions, events and travel communities, with a trip captain and a clear departure to keep every group organised.",
        features: [
          "Curated group adventures and travel communities",
          "Fixed departures with live seat availability",
          "Trip captains who run each departure",
          "Enquiries and bookings connected to your TravelsTREM account",
        ],
        linkKey: "trevio",
        cta: "Book a Trevio demo",
      },
      trevista: {
        status: "Tours & holidays",
        name: "Trevista",
        tagline: "Tours and holiday packages, personalised to you",
        about:
          "Trevista is the tours and holiday-packages product. Explore curated domestic and international journeys, review the itinerary and inclusions, and ask for a personalised version when the standard package is not exactly what you need.",
        features: [
          "Curated tour discovery with structured itineraries",
          "Detailed stays, inclusions and package options",
          "Personalised enquiry and quote journey",
          "Connected booking management through TravelsTREM",
        ],
        linkKey: "trevista",
        cta: "Book a Trevista demo",
      },
      hub: {
        status: "Connected account",
        name: "Dashboard",
        tagline: "One operational view for the whole journey",
        about:
          "The TravelsTREM hub is the single account behind every product. It keeps discovery, enquiries, quotes, bookings, documents and support connected so you never lose context as your trip moves forward.",
        features: [
          "One TravelsTREM account across all products",
          "Enquiries, quotes and bookings in a single timeline",
          "Travel documents and booking progress together",
          "Support connected to every journey",
        ],
        linkKey: "hub",
        cta: "Book a Dashboard demo",
      },
      partnertrem: {
        status: "For travel agencies",
        name: "Partner TREM",
        tagline: "A workspace that runs the daily agency operation",
        about:
          "Partner TREM is the agency workspace behind TravelsTREM. It keeps tours, enquiries, customers and bookings in one place, and lets eligible journeys become discoverable by travellers through Trevista.",
        features: [
          "Role-based workspace for agency admins and agents",
          "Create, organise and publish structured tour inventory",
          "Manage enquiries, quotes and bookings with context",
          "Publish eligible tours to travellers through Trevista",
        ],
        linkKey: "partnerApplication",
        cta: "Book a PartnerTREM demo",
        detailsLinkKey: "partnershipDetails",
        detailsCta: "Book a platform demo",
      },
      admintrem: {
        status: "Admin dashboard",
        name: "AdminTREM",
        tagline: "Central administration and oversight for the TravelsTREM ecosystem",
        about:
          "AdminTREM is the platform owner's administration dashboard. It provides a central place to govern partner organisations, internal teams, access, product configuration, approvals, workflows and system-wide operational reporting.",
        features: [
          "Partner onboarding, status and approval controls",
          "Internal teams, roles and platform-wide access",
          "Product, workflow and operational configuration",
          "Cross-platform oversight, reporting and governance",
        ],
        linkKey: "bookDemo",
        cta: "Book an AdminTREM demo",
      },
      bookingengine: {
        status: "Transaction infrastructure",
        name: "Booking Engine",
        tagline: "The connected lifecycle from accepted quote to fulfilled journey",
        about:
          "The TravelsTREM Booking Engine brings traveller details, commercial confirmation, payments, documents, operational milestones and post-booking support into one governed lifecycle.",
        features: [
          "Configurable quote-to-booking transitions",
          "Traveller, payment and document workflows",
          "Operational milestones and fulfilment status",
          "Connected Finance and Process Engine foundations",
        ],
        linkKey: "bookingEngine",
        cta: "Book a Booking Engine demo",
      },
    },
    productPreviews: {
      trevio: [
        "Community Trips &amp; Adventures",
        "Shared departures, trip captains and travel communities",
        ["Overview", "Departures", "Community", "Captains"],
        "Featured departure",
        "Kedarkantha Winter Trek",
        [
          ["12", "Upcoming departures"],
          ["06", "Seats left"],
          ["4.9", "Community rating"],
        ],
        [
          ["Weekend trek · Kalsubai", "₹4,299 · Departure 18th"],
          ["Goa community trip", "Waitlist open"],
          ["Himalayan expedition", "Captain assigned"],
        ],
      ],
      trevista: [
        "Tours &amp; Packages",
        "Curated itineraries, personalised quotes, connected bookings",
        ["Overview", "Packages", "Itinerary", "Stays"],
        "Featured journey",
        "Royal Rajasthan Heritage Circuit",
        [
          ["6D", "Duration"],
          ["18", "Seats"],
          ["4.8", "Traveller rating"],
        ],
        [
          ["Standard package", "₹24,992"],
          ["Premium package", "₹36,536"],
          ["Custom journey", "Start enquiry"],
        ],
      ],
      trehub: [
        "Flights &amp; Hotels",
        "Search, compare and shortlist travel essentials in one view",
        ["Overview", "Flights", "Hotels", "Shortlist"],
        "Search · Jaipur → Delhi → Goa",
        "One comparison for travel essentials.",
        [
          ["14", "Flight options"],
          ["32", "Hotels found"],
          ["4.6", "Shortlist rating"],
        ],
        [
          ["IndiGo · 6E 2042 · 07:40", "₹4,899"],
          ["Vistara · UK 879 · 09:15", "₹5,420"],
          ["Hotel shortlist", "2 stays saved"],
        ],
      ],
    },
    audiences: {
      traveller: {
        title: "A journey that stays connected after you click “Get a Quote”.",
        copy: "Discover a tour, tell the responsible agent what you need, compare customised options, accept a quote, pay and continue receiving the documents and updates attached to the same booking.",
        benefits: [
          [
            "Discover",
            "Browse travel products and eligible tours without needing to understand the agency structure behind each listing.",
          ],
          [
            "Customise",
            "Your requirement becomes an actionable enquiry for the responsible agency and agent.",
          ],
          [
            "Continue",
            "Quote, payment, documents and booking status remain connected to the same journey.",
          ],
        ],
        visual: `
              <div class="journey-top"><div><small>Traveller journey</small><strong>Kashmir · 5 nights / 6 days</strong></div><span class="journey-status">Quote ready</span></div>
              <div class="journey-steps"><div class="journey-step"><b>1</b><strong>Discover</strong><span>Trevista</span></div><div class="journey-step"><b>2</b><strong>Enquire</strong><span>Requirements</span></div><div class="journey-step"><b>3</b><strong>Review</strong><span>Quote options</span></div><div class="journey-step"><b>4</b><strong>Pay</strong><span>Secure booking</span></div><div class="journey-step"><b>5</b><strong>Travel</strong><span>Documents</span></div></div>
              <div class="journey-card"><div class="journey-card-head"><div><small>Customised quote</small><strong>Choose the experience that fits you</strong></div><small>Valid for review</small></div><div class="quote-options"><div class="quote-option"><span>Standard</span><strong>₹72,500</strong></div><div class="quote-option active"><span>Premium</span><strong>₹89,900</strong></div><div class="quote-option"><span>Advance</span><strong>₹1,08,400</strong></div></div><div class="quote-total"><small>Final amount shown before payment</small><b>₹89,900</b></div></div>`,
      },
      partner: {
        title: "Run the agency workflow and publish into the same ecosystem.",
        copy: "Partner TREM gives approved agencies a structured operating surface for tours, customers, enquiries, quotes, bookings, payments and post-booking fulfilment—with eligible inventory connected to the TravelsTREM marketplace.",
        benefits: [
          ["Operate", "Manage agents, tours and customer journeys from one agency workspace."],
          [
            "Convert",
            "Turn enquiries into customised quotes and accepted bookings without losing context.",
          ],
          [
            "Distribute",
            "Publish eligible travel inventory into the TravelsTREM customer experience.",
          ],
        ],
        visual: `
              <div class="journey-top"><div><small>Partner TREM</small><strong>Agency operating journey</strong></div><span class="journey-status">Marketplace connected</span></div>
              <div class="journey-steps"><div class="journey-step"><b>1</b><strong>Tour</strong><span>Create</span></div><div class="journey-step"><b>2</b><strong>Publish</strong><span>Go live</span></div><div class="journey-step"><b>3</b><strong>Enquiry</strong><span>Assign</span></div><div class="journey-step"><b>4</b><strong>Quote</strong><span>Customise</span></div><div class="journey-step"><b>5</b><strong>Booking</strong><span>Deliver</span></div></div>
              <div class="journey-card"><div class="journey-card-head"><div><small>Agency queue</small><strong>What needs attention</strong></div><small>Live</small></div><div class="mini-table" style="color:var(--trem-text)"><div class="mini-row" style="background:var(--trem-surfaceSubtle)"><strong>Kashmir honeymoon</strong><span>Quote accepted</span><span class="status">Payment</span></div><div class="mini-row" style="background:var(--trem-surfaceSubtle)"><strong>Andaman family</strong><span>New enquiry</span><span class="status">Assign</span></div><div class="mini-row" style="background:var(--trem-surfaceSubtle)"><strong>Dubai holiday</strong><span>Booking</span><span class="status">Documents</span></div></div></div>`,
      },
    },
    pages: {
      home: {
        output: "index.html",
        frameStart: "src/pages/home/start.html",
        sections: [
          "src/sections/home/hero.html",
          "src/sections/home/marquee.html",
          "src/sections/home/promises.html",
          "src/sections/home/travellers.html",
          "src/sections/home/products.html",
          "src/sections/home/platform-preview.html",
          "src/sections/home/journey.html",
          "src/sections/home/quality.html",
          "src/sections/shared/builders.html",
          "src/sections/home/partner-trem.html",
          "src/sections/home/about.html",
        ],
        frameEnd: "src/pages/home/end.html",
      },
      partnership: {
        output: "partnership.html",
        frameStart: "src/pages/partnership/start.html",
        sections: [
          "src/sections/partnership/hero.html",
          "src/sections/partnership/platform.html",
          "src/sections/partnership/capabilities.html",
          "src/sections/shared/builders.html",
          "src/sections/partnership/workflow.html",
          "src/sections/partnership/distribution.html",
          "src/sections/partnership/pricing.html",
          "src/sections/partnership/agency.html",
          "src/sections/partnership/leadership.html",
          "src/sections/partnership/contact.html",
        ],
        frameEnd: "src/pages/partnership/end.html",
      },
    },
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = TRAVELSTREM_WEBSITE;
  }

  if (!global?.document) return;

  const supplied = global.TRAVELSTREM_SITE_CONFIG || {};
  global.TRAVELSTREM_SITE_CONFIG = {
    ...TRAVELSTREM_WEBSITE,
    ...supplied,
    links: {
      ...TRAVELSTREM_WEBSITE.links,
      ...(supplied.links || {}),
    },
  };

  const applyConfiguredLinks = () => {
    document.querySelectorAll("a[data-link]").forEach((anchor) => {
      const destination = global.TRAVELSTREM_SITE_CONFIG.links?.[anchor.dataset.link];
      const link = typeof destination === "string" ? { href: destination } : destination;
      if (!link?.href) return;
      anchor.href =
        global.location?.protocol === "file:" && link.localHref ? link.localHref : link.href;
      if (link.external) {
        anchor.target = "_blank";
        anchor.rel = "noopener noreferrer";
      }
    });
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", applyConfiguredLinks, { once: true });
  } else {
    applyConfiguredLinks();
  }
})(typeof window !== "undefined" ? window : globalThis);
