(function configureTravelsTremWebsite(global) {
  const TRAVELSTREM_WEBSITE = {
    navigation: {
      home: {
        home: "#top", caption: "Travel, thoughtfully connected.", menuLabel: "Explore TravelsTREM",
        cta: "Explore tours", ctaKey: "trevista", ctaHref: "https://app.travelstrem.com/?tab=trevista&product=trevista",
        links: [
          { href: "#travellers", label: "Experience" },
          { href: "#products", label: "Our products" },
          { href: "#journey", label: "Your journey" },
          { href: "#about", label: "Our story" },
          { href: "partnership.html", label: "For agencies ↗" },
        ],
      },
      partnership: {
        home: "index.html", caption: "The workspace behind every journey.", menuLabel: "Explore PartnerTREM",
        cta: "Book a demo", ctaKey: "partnerDemo", ctaHref: "mailto:akshat.goyal@travelstrem.com",
        links: [
          { href: "#partner-trem", label: "Platform" },
          { href: "#workflow", label: "Workflow" },
          { href: "#distribution", label: "Distribution" },
          { href: "#pricing", label: "Plans" },
          { href: "index.html", label: "For travellers ↗" },
        ],
      },
    },
    analytics: {
      enabled: true,
      measurementId: "G-RP0Z50DM4P",
      hosts: ["travelstrem.com", "www.travelstrem.com"],
    },
    ads: {
      enabled: true,
      publisherId: "ca-pub-2541753556383634",
      hosts: ["travelstrem.com", "www.travelstrem.com"],
      label: "Advertisement",
      placements: {
        home: [
          { name: "home-discovery", after: "src/sections/home/travellers.html", slot: "" },
          { name: "home-journey", after: "src/sections/home/quality.html", slot: "" },
        ],
        partnership: [
          { name: "partner-workflow", after: "src/sections/partnership/workflow.html", slot: "" },
        ],
      },
    },
    brand: {
      name: "TravelsTREM",
      partnerName: "PartnerTREM",
      operator: "Shree Air Tours & Travels",
    },
    contact: {
      email: "akshat.goyal@travelstrem.com",
      phoneHref: "+919602225763",
      phoneLabel: "+91 90576 35580",
      locationLabel: "Shree Air Tours and Travels, Jaipur",
    },
    leadership: {
      chairperson: { name: "Mrs. Nisha Goyal", role: "Chairperson" },
      founder: { name: "Mr. Shreekant Goyal", role: "Founder &amp; Managing Director" },
      executive: { name: "Mr. Akshat Goyal", role: "CEO &amp; Executive Director" },
    },
    pricing: {
      start: { name: "Partner Start", monthlyPrice: "₹1,999" },
      growth: { name: "Partner Growth", monthlyPrice: "₹3,999" },
      signature: { name: "Partner Signature", monthlyPrice: "₹5,999" },
    },
    links: {
      main: { href: "#top" },
      home: { href: "#top" },
      about: { href: "#about" },
      ecosystem: { href: "#ecosystem" },
      agency: { href: "#agency" },
      people: { href: "#people" },
      partners: { href: "#partners" },
      contact: { href: "#contact" },
      partnershipDetails: { href: "https://travelstrem.com/partnership" },
      partnership: {
        href: "/partnership",
        localHref: "partnership.html",
      },
      trevio: {
        href: "https://app.travelstrem.com/?tab=trevio&product=trevio",
        external: true,
      },
      trevista: {
        href: "https://app.travelstrem.com/?tab=trevista&product=trevista",
        external: true,
      },
      trehub: {
        href: "https://app.travelstrem.com/?tab=trehub&product=trehub",
        external: true,
      },
      hub: {
        href: "https://app.travelstrem.com/?tab=dashboard",
        external: true,
      },
      partnerApplication: {
        href: "https://auth.travelstrem.com/partnership",
        external: true,
      },
      partnerDemo: {
        href: "https://mail.google.com/mail/?view=cm&fs=1&to=akshat.goyal@travelstrem.com&su=PartnerTREM%20demo%20request&body=Hello%20PartnerTREM%20team%2C%0A%0AI%20would%20like%20to%20book%20a%20PartnerTREM%20demo.%0A%0AName%3A%20%0AAgency%3A%20%0APhone%3A%20%0APreferred%20date%20and%20time%3A%20%0A%0AThank%20you.",
        external: true,
      },
      email: { href: "mailto:akshat.goyal@travelstrem.com" },
      phone: { href: "tel:+919602225763" },
      location: {
        href: "https://maps.app.goo.gl/ebvDhsdzAe27XRSn7",
        external: true,
      },
    },
    content: {
      pages_home_end: {
        strong1: "TravelsTREM",
        small1: "Travel is personal. The platform should be too.",
        p1: "A connected travel platform for travellers and approved travel partners, powered by the operating experience of Shree Air Tours &amp; Travels.",
        h31: "Explore",
        a1: "Travel services",
        a2: "Products",
        a3: "Explore tours ↗",
        a4: "Platform workflow",
        a5: "About TravelsTREM",
        a6: "PartnerTREM ↗",
        h32: "Contact",
        a7: "Book Partner Demo ↗",
        span1: "Trevio · Trevista · TreHub · TravelsTREM Hub · Partner TREM",
      },
      pages_home_start: {
        title1: "TravelsTREM | Travel is personal. The platform should be too.",
        strong1: "TravelsTREM",
        small1: "Powered by Shree Air Tours &amp; Travels",
        a1: "Travel services",
        a2: "Products",
        a3: "Explore tours",
        a4: "Platform workflow",
        a5: "About TravelsTREM",
        a6: "PartnerTREM",
        a7: "Explore TravelsTREM ↗",
        a8: "Travel services",
        a9: "Products",
        a10: "Explore tours",
        a11: "Platform workflow",
        a12: "About TravelsTREM",
        a13: "PartnerTREM",
        a14: "Explore TravelsTREM ↗",
      },
      pages_partnership_end: {
        strong1: "TravelsTREM",
        small1: "Travel is personal. The platform should be too.",
        p1: "A connected travel platform bringing travellers together with Shree Air Tours &amp; Travels and approved partner agencies through customer products and structured partner operations.",
        h31: "Explore",
        a1: "Platform",
        a2: "Trevista ↗",
        a3: "Partner TREM",
        a4: "Leadership",
        h32: "Contact",
        a5: "Apply for partnership ↗",
        span1: "TravelsTREM currently operates as a managed travel platform.",
      },
      pages_partnership_start: {
        title1: "Partner TREM | TravelsTREM for Travel Agencies",
        strong1: "PartnerTREM",
        small1: "Operated by Shree Air Tours &amp; Travels.",
        a1: "Capabilities",
        a2: "Workflow",
        a3: "Distribution",
        a4: "Pricing",
        a5: "Book a PartnerTREM demo →",
        a6: "Capabilities",
        a7: "Workflow",
        a8: "Distribution",
        a9: "Pricing",
        a10: "View Trevista ↗",
        a11: "Book a PartnerTREM demo →",
      },
      sections_home_about: {
        strong1: "20+ years",
        span1: "Travel-industry experience",
        span2: "Shree Air Tours &amp; Travels",
        div1: "SERVICE → OPERATIONS → SUPPLIERS → PARTNER COORDINATION",
        h31: "Experience behind every TravelsTREM journey.",
        p1: "Shree Air Tours &amp; Travels brings more than two decades of practical travel knowledge to the platform—keeping technology grounded in what travellers need and what agencies must deliver before, during and after every journey.",
        div2: "NG",
        p2: "Guides the organisation’s service culture, stewardship and long-term direction.",
        div3: "SG",
        p3: "Leads Shree Air Tours &amp; Travels, its travel relationships and agency operations with more than two decades of industry experience.",
        div4: "AG",
        p4: "Leads the TravelsTREM product and technology vision across traveller and partner workflows.",
      },
      sections_home_contact: {
        span1: "For travellers",
        h31: "Find your next journey with TravelsTREM.",
        p1: "Explore community adventures with Trevio, holiday packages with Trevista, and flights and stays with TreHub—all connected to your TravelsTREM account.",
        a1: "Start with TravelsTREM ↗",
        span2: "For agencies",
        h32: "See Partner TREM in your agency workflow.",
        p2: "Book a product demo to see tour management, enquiries, quotes and bookings from the partner side.",
        a2: "Apply for partnership ↗",
      },
      sections_home_hero: {
        span1: "Travel is personal. The platform should be too.",
        h11: "Your trip should feel",
        span2: "personal",
        p1: "TravelsTREM brings tour discovery, personalised requirements, quotes, bookings and trip management into one connected journey backed by real travel agencies and agents.",
        a1: "Explore TravelsTREM ↗",
        a2: "See how it works",
        small1: "app.travelstrem.com · Journey overview",
        span3: "T",
        span4: "Journey connected",
        span5: "Overview",
        span6: "Discover",
        span7: "Enquiries",
        span8: "Bookings",
        span9: "Support",
        small2: "Your travel workspace",
        h31: "Everything around one journey.",
        strong1: "04",
        span10: "Saved journeys",
        strong2: "02",
        span11: "Active enquiries",
        strong3: "01",
        span12: "Upcoming trip",
        strong4: "Royal Rajasthan Heritage Circuit",
        span13: "Quote ready",
        strong5: "Varanasi Spiritual Discovery",
        span14: "Agent assigned",
        strong6: "Meghalaya Waterfalls",
        span15: "Saved",
        b1: "Built for the whole journey",
        span16:
          "Discover a tour, ask for changes, review the quote and continue from the same TravelsTREM account.",
      },
      sections_home_journey: {
        span1: "The traveller journey",
        h21: "From “I like this trip” to “everything is ready.”",
        p1: "A clear workflow keeps the traveller and the responsible agency aligned as the trip becomes more specific.",
        div1: "01",
        h31: "Discover",
        p2: "Explore Trevista packages and find a journey that matches your travel intent.",
        div2: "02",
        h32: "Enquire",
        p3: "Tell the travel partner what you need changed, added or clarified.",
        div3: "03",
        h33: "Personalise",
        p4: "The assigned agent works from your requirements and the base tour.",
        div4: "04",
        h34: "Review quote",
        p5: "Review the commercial option prepared around your requested journey.",
        div5: "05",
        h35: "Book &amp; pay",
        p6: "Move the accepted quote into the booking and payment lifecycle.",
        div6: "06",
        h36: "Travel",
        p7: "Keep booking progress, travel documents and trip information accessible.",
      },
      sections_home_marquee: {
        span1: "Curated holiday packages",
        span2: "Personalised quote journey",
        span3: "Connected bookings &amp; support",
        span4: "One travel account",
        span5: "Approved travel partners",
        span6: "Built by real agencies",
        span7: "Domestic &amp; international tours",
        span8: "Managed travel platform",
        span9: "Curated holiday packages",
        span10: "Personalised quote journey",
        span11: "Connected bookings &amp; support",
        span12: "One travel account",
        span13: "Approved travel partners",
        span14: "Built by real agencies",
        span15: "Domestic &amp; international tours",
        span16: "Managed travel platform",
      },
      "sections_home_partner-trem": {
        span1: "For travel agencies · Partner TREM",
        h21: "Run your agency. Reach more travellers.",
        p1: "Partner TREM keeps tours, enquiries, customers and bookings in one workspace, while eligible journeys become discoverable through TravelsTREM.",
        i1: "1",
        strong1: "Manage the daily operation",
        span2: "Keep your team, customers and travel records connected.",
        i2: "2",
        strong2: "Create and publish tours",
        span3: "Build structured inventory and publish eligible tours to Trevista.",
        i3: "3",
        strong3: "Convert interest into travel",
        span4: "Move enquiries through quotes and bookings without losing context.",
        a1: "Apply for partnership ↗",
        a2: "See full capabilities ↗",
        div1: "Partner TREM · Agency workspace",
        span5: "T",
        span6: "Agency workspace",
        span7: "Overview",
        span8: "Tours",
        span9: "Enquiries",
        span10: "Customers",
        small1: "Today at your agency",
        h31: "Everything important, in view.",
        strong4: "12",
        span11: "Active tours",
        strong5: "08",
        span12: "Open enquiries",
        strong6: "24",
        span13: "Customers",
        strong7: "Royal Rajasthan enquiry",
        span14: "Quote ready",
        strong8: "Varanasi booking",
        span15: "Confirmed",
        strong9: "Meghalaya tour",
        span16: "Published",
        strong10: "Agency &amp; team",
        span17: "Role-based workspace for agency admins and agents.",
        strong11: "Tours",
        span18: "Create, organise and publish structured inventory.",
        strong12: "Enquiries",
        span19: "Receive and manage customer requirements from TravelsTREM.",
        strong13: "Quotes &amp; bookings",
        span20: "Carry customer context from requirement to confirmation.",
      },
      "sections_home_platform-preview": {
        span1: "See the platform",
        h21: "The experience continues after you find the tour.",
        p1: "Switch between the Trevista discovery surface and the TravelsTREM traveller hub. The goal is one continuous experience rather than a collection of disconnected pages.",
        button1: "Manage your journey",
        button2: "Tour listing",
        button3: "Tour details",
        button4: "Tour booking",
        span2: "TravelsTREM · Actual product interfaces",
        div1: "Home &nbsp;›&nbsp; My Bookings",
        small1: "TOUR SUPPORT",
        h31: "My bookings &amp; enquiries",
        p2: "Track every request you have sent and any booking confirmed for your account.",
        span3: "6 total",
        h41: "All records &nbsp;⑥",
        p3: "Search your enquiries and confirmed bookings.",
        span4: "Search by reference, tour or contact",
        span5: "All records",
        span6: "Newest",
        span7: "REFERENCE",
        span8: "TOUR OR SERVICE",
        span9: "TYPE",
        span10: "SPECIALIST",
        span11: "TRAVELLERS",
        span12: "TRAVEL DATES",
        span13: "STATUS",
        span14: "CREATED",
        span15: "ENQ-0BBEF6",
        b1: "Varanasi Spiritual Discovery",
        span16: "Trevista",
        span17: "Enquiry",
        span18: "Tanshu Goyal",
        span19: "2",
        span20: "19–26 Sept 2026",
        span21: "● New",
        span22: "26 Aug 2026",
        span23: "ENQ-B10173",
        b2: "Custom tour enquiry",
        span24: "Trevista",
        span25: "Enquiry",
        span26: "Akshat Goyal",
        span27: "1",
        span28: "Flexible",
        span29: "● New",
        span30: "26 Aug 2026",
        span31: "ENQ-42E4B3",
        b3: "Delhi to Leh Himalayan Road Expedition",
        span32: "Trevista",
        span33: "Enquiry",
        span34: "Shreekant Goyal",
        span35: "2",
        span36: "19–26 Sept 2026",
        span37: "● New",
        span38: "24 Aug 2026",
        span39: "ENQ-9D6A98",
        b4: "Royal Rajasthan Heritage Circuit",
        span40: "Trevista",
        span41: "Enquiry",
        span42: "Shreekant Goyal",
        span43: "2",
        span44: "10–15 Oct 2026",
        span45: "● New",
        span46: "24 Aug 2026",
        div2: "Find your perfect adventure",
        span47: "All tours",
        span48: "Domestic",
        span49: "International",
        span50: "Featured",
        span51: "Adventure",
        span52: "Family",
        span53: "Luxury",
        div3: "Can't find a tour that fits?",
        b5: "Create a custom journey.",
        span54: "⌁ &nbsp; Filters",
        span55: "⌕ &nbsp; Search by tour, destination, or experience…",
        b6: "10 tours",
        div4: "Showing&nbsp; 8 of 10",
        div5: "◉ &nbsp; You're signed in. Save favourites and manage your Trevista bookings from your dashboard.",
        span56: "☆ Featured",
        small2: "SHILLONG TO CHERRAPUNJI",
        h42: "Meghalaya Waterfalls and Living Roots",
        div6: "☆ 0.0 · Cherrapunji, India · 8 days",
        span57: "Standard",
        b7: "₹24,992",
        span58: "Premium",
        b8: "₹36,536",
        span59: "Advance",
        b9: "₹52,844",
        span60: "Explore this Tour",
        span61: "☆ Featured",
        small3: "VARANASI TO SARNATH",
        h43: "Varanasi Spiritual Discovery",
        div7: "☆ 0.0 · Sarnath, India · 8 days",
        span62: "Standard",
        b10: "₹24,992",
        span63: "Premium",
        b11: "₹36,536",
        span64: "Advance",
        b12: "₹52,844",
        span65: "Explore this Tour",
        span66: "☆ Featured",
        small4: "PANAJI TO SOUTH GOA",
        h44: "Goa Coast and Heritage Getaway",
        div8: "☆ 0.0 · South Goa, India · 8 days",
        span67: "Standard",
        b13: "₹24,992",
        span68: "Premium",
        b14: "₹36,536",
        span69: "Advance",
        b15: "₹52,844",
        span70: "Explore this Tour",
        span71: "☆ Featured",
        small5: "DELHI TO LEH",
        h45: "Delhi to Leh Himalayan Road Expedition",
        div9: "☆ 0.0 · Leh, India · 8 days",
        span72: "Standard",
        b16: "₹24,992",
        span73: "Premium",
        b17: "₹36,536",
        span74: "Advance",
        b18: "₹52,844",
        span75: "Explore this Tour",
        small6: "Trevista &nbsp;›&nbsp; Tours &nbsp;›&nbsp; Varanasi Spiritual Discovery",
        span76: "⌕ &nbsp; Search tours, bookings, enquiries, support…",
        span77: "Overview",
        span78: "Packages",
        span79: "Itinerary",
        span80: "Inclusions",
        span81: "Hotels &amp; stays",
        span82: "Policies",
        small7: "Route",
        b19: "Varanasi to Sarnath",
        small8: "Duration",
        b20: "8 days · 7 nights",
        small9: "Dates",
        b21: "19 Sept to 26 Sept",
        small10: "Seats",
        b22: "18 available",
        b23: "Operated by",
        br1: "Shree Air tours &amp; travels",
        b24: "Uploaded by agent",
        br2: "Tanshu Goyal",
        h46: "✦ &nbsp; Highlights",
        b25: "Delhi to Leh Overland Journey",
        span83: "Cross the Himalayas through Manali and Jispa.",
        b26: "Atal Tunnel &amp; Lahaul Valley",
        span84: "Experience the changing landscapes beyond Manali.",
        b27: "High Himalayan Passes",
        span85: "Travel through Baralacha La and Tanglang La.",
        b28: "Leh &amp; Sham Valley",
        span86: "Explore Leh Palace and Magnetic Hill.",
        b29: "Three Package Choices",
        span87: "Choose the travel style that suits you.",
        h32: "Tour packages",
        small11: "STANDARD",
        b30: "₹24,992",
        h47: "Essential journey",
        p4: "Comfortable stays and shared travel for a great-value experience.",
        li1: "Standard accommodation",
        li2: "Shared road transport",
        li3: "Essential sightseeing",
        button5: "Choose this plan",
        small12: "PREMIUM · RECOMMENDED",
        b31: "₹36,536",
        h48: "Premium journey",
        p5: "Upgraded stays, premium transport and expanded sightseeing.",
        li4: "Premium accommodation",
        li5: "Premium road transport",
        li6: "Airport drop included",
        button6: "Selected",
        small13: "ADVANCE",
        b32: "₹52,844",
        h49: "Signature journey",
        p6: "Private premium travel with elevated stays and personal service.",
        li7: "Signature accommodation",
        li8: "Private SUV transport",
        li9: "Private sightseeing",
        button7: "Choose this plan",
        small14: "YOUR JOURNEY",
        h33: "Andaman Island Discovery",
        p7: "Booking reference ENQ-A32BFA · Signature package",
        span88: "Quote received",
        h410: "Your booking journey",
        b33: "Enquiry completed",
        span89: "Your travel requirements were shared with the partner.",
        b34: "Review your quotation",
        span90: "Download, request a change or accept the prepared quote.",
        b35: "Add traveller details",
        span91: "Complete traveller information after accepting the quote.",
        b36: "Travel updates",
        span92: "Follow documents, tickets and live booking progress.",
        h411: "Your personalised quotation",
        small15: "PREPARED FOR YOUR REQUEST",
        strong1: "Signature island journey for five travellers",
        span93: "Journey prepared by your travel partner",
        b37: "₹3,28,552",
        span94: "TravelsTREM service fee",
        b38: "₹3,286",
        span95: "Applicable tax",
        b39: "₹591",
        span96: "Total quotation",
        b40: "₹3,32,429",
        span97: "Download PDF",
        span98: "Request changes",
        span99: "Accept quote",
      },
      sections_home_products: {
        span1: "Our Products",
        h21: "A product for every part of your journey.",
        p1: "TravelsTREM connects a family of products around one travel account. Explore each product below and open its details to see exactly what it provides.",
        span2: "Community travel",
        h31: "Trevio",
        p2: "Community trips, adventures, treks, expeditions and travel communities with shared departures.",
        li1: "Fixed departures with live availability",
        li2: "Trip captains and travel communities",
        span3: "View details",
        span4: "Tours & holidays",
        h32: "Trevista",
        p3: "Curated holiday packages with detailed itineraries, personalised quotes and connected bookings.",
        li3: "Curated domestic &amp; international tours",
        li4: "Personalised enquiry and quote journey",
        span5: "View details",
        span6: "Flights & hotels",
        h33: "TreHub",
        p4: "Flight and hotel search connected to your journey, with fares, timings and stay options in one comparison view.",
        li5: "Flight options and hotel stays together",
        li6: "Compare, shortlist and attach to a trip",
        span7: "View details",
        span8: "Connected",
        h34: "TravelsTREM Hub",
        p5: "One account that links discovery, enquiries, quotes, bookings, documents and support across products.",
        li7: "Single account across every product",
        li8: "Bookings, documents and support in one place",
        span9: "View details",
        span10: "For agencies",
        h35: "Partner TREM",
        p6: "A role-based workspace where agencies run tours, enquiries, customers and bookings together.",
        li9: "Create, organise and publish tours",
        li10: "Enquiries, quotes and bookings management",
        span11: "View details",
        a1: "Open product ↗",
      },
      sections_home_promises: {
        small1: "01 · Discover",
        strong1: "Curated tours &amp; packages",
        small2: "02 · Personalise",
        strong2: "Your requirements, your quote",
        small3: "03 · Book",
        strong3: "A connected booking journey",
        small4: "04 · Manage",
        strong4: "Trips, updates &amp; records together",
      },
      sections_home_quality: {
        span1: "What we care about",
        h21: "Technology should make travel clearer, not more complicated.",
        p1: "TravelsTREM brings personal service, connected journeys and accountable travel partners into every booking.",
        span2: "01 / PERSONAL",
        h31: "Built around requirements",
        p2: "A holiday package is a starting point. The platform supports a journey that can become specific to the traveller.",
        span3: "02 / CONNECTED",
        h32: "One journey, not isolated tools",
        p3: "Discovery, enquiry, quote, booking and fulfilment work as stages of the same record.",
        span4: "03 / ACCOUNTABLE",
        h33: "Real partner ownership",
        p4: "The responsible agency and agent stay connected to the traveller journey instead of disappearing behind a generic listing.",
        span5: "04 / PRACTICAL",
        h34: "Travel operations underneath",
        p5: "TravelsTREM is not only a storefront. Partner-side workflows exist so what the traveller sees can be supported operationally.",
      },
      sections_home_travellers: {
        span1: "What TravelsTREM does for travellers",
        h21: "Less switching between people, chats and files. More clarity around your journey.",
        p1: "TravelsTREM connects every stage of your trip. Instead of stopping at a tour listing, the platform keeps discovery, personalisation, booking and post-booking activity connected.",
        b1: "01",
        h31: "Discover curated tours",
        p2: "Browse holiday packages with itinerary, stays, inclusions, destinations and trip information presented in one structured experience.",
        b2: "02",
        h32: "Ask for your version",
        p3: "Send your requirements to the responsible travel partner so the itinerary can be adjusted around flights, stays, transfers or other trip needs.",
        b3: "03",
        h33: "Review a structured quote",
        p4: "Move from enquiry to an organised quote instead of scattered messages, with the trip commercial journey tied back to your request.",
        b4: "04",
        h34: "Continue into booking",
        p5: "Once you choose the right option, your accepted quote becomes part of the booking journey instead of becoming another disconnected document.",
        b5: "05",
        h35: "Keep trip records together",
        p6: "Your dashboard brings together enquiries, confirmed journeys, booking progress and travel documents as the journey moves forward.",
        b6: "06",
        h36: "Travel with accountable partners",
        p7: "Tours are connected to approved travel agencies and their agents, keeping operational responsibility attached to the booking journey.",
      },
      sections_partnership_agency: {
        span1: "Partner TREM demo",
        h21: "See how Partner TREM fits your agency workflow.",
        p1: "Walk through the real operating flow: tour management, enquiries, quotes, bookings, payments, fulfilment and Trevista distribution.",
        a1: "Apply for partnership ↗",
        a2: "Talk to our team",
        strong1: "Agency &amp; agent management",
        span2: "Operate teams with role-aware access and ownership.",
        strong2: "Tour publishing",
        span3: "Create and manage travel inventory that can become customer-facing.",
        strong3: "Quote &amp; booking journey",
        span4: "Move customer requirements through a structured commercial flow.",
        strong4: "Post-payment operations",
        span5: "Track documents, balances and fulfilment beyond checkout.",
      },
      sections_partnership_capabilities: {
        span1: "Partner TREM",
        h21: "Not another dashboard. A travel-agency workspace connected to your marketplace.",
        p1: "Manage the operational journey in one place, while eligible tours can move directly into the TravelsTREM customer experience.",
        strong1: "Real Partner TREM product · Guided Tour Builder",
        span2: "Tour creation workspace",
        strong2: "Partner TREM",
        span3: "Tour builder",
        span4: "Inventory",
        span5: "Enquiries",
        span6: "Customers",
        span7: "Reports",
        small1: "Guided workflow",
        h31: "Build a complete travel product.",
        div1: "01 · Basics",
        div2: "02 · Itinerary",
        div3: "03 · Packages",
        div4: "04 · Publish",
        div5: "Tour name",
        strong3: "Royal Rajasthan Heritage Circuit",
        div6: "Product owner",
        strong4: "Shree Air Tours &amp; Travels",
        div7: "Journey type",
        strong5: "Fixed departure",
        div8: "Distribution",
        strong6: "TravelsTREM + Trevista",
        span8: "01 · Agency",
        strong7: "Operations",
        span9: "02 · Team",
        strong8: "People &amp; access",
        span10: "03 · Products",
        strong9: "Tour inventory",
        span11: "04 · Customers",
        strong10: "Enquiries &amp; CRM",
        span12: "05 · Commercial",
        strong11: "Quotes &amp; pricing",
        span13: "06 · Bookings",
        strong12: "Journey fulfilment",
        span14: "07 · Finance",
        strong13: "Payments &amp; records",
        small2: "Agency command centre",
        h32: "Know what needs attention.",
        span15: "Live workspace",
        h41: "Open enquiries",
        strong14: "18",
        p2: "Incoming customer requirements waiting for action.",
        h42: "Quotes in progress",
        strong15: "11",
        p3: "Draft, sent and revised commercial proposals.",
        h43: "Bookings in journey",
        strong16: "9",
        p4: "Confirmed bookings that still need delivery actions.",
        h44: "Published tours",
        strong17: "24",
        p5: "Your marketplace-ready travel inventory.",
        h45: "Priority queue",
        strong18: "Kashmir · 5N/6D",
        span16: "Quote accepted",
        span17: "Collect advance",
        strong19: "Bali · 6N/7D",
        span18: "New enquiry",
        span19: "Assign agent",
        strong20: "Dubai · 4N/5D",
        span20: "Booked",
        span21: "Upload tickets",
        h46: "Workflow health",
        strong21: "One view",
        p6: "Agency admins can see the movement from enquiry to delivery instead of tracking disconnected spreadsheets.",
        small3: "Agency operations",
        h33: "Manage the business and the people responsible for every journey.",
        span22: "Role-based access",
        h47: "Agency workspace",
        strong22: "Shree Air Tours &amp; Travels",
        p7: "Verified agency profile · Active partner",
        h48: "Team overview",
        strong23: "12",
        span23: "Total members",
        strong24: "10",
        span24: "Active accounts",
        strong25: "2",
        span25: "Pending invitations",
        p8: "Invite agents, manage their status and keep workspace ownership clear.",
        h49: "Agency team",
        strong26: "Shreekant Goyal",
        span26: "Partner admin",
        span27: "Active",
        strong27: "Tanshu Goyal",
        span28: "Travel agent",
        span29: "Active",
        strong28: "Operations desk",
        span30: "Support team",
        span31: "Invited",
        h410: "Access controls",
        strong29: "Tour inventory",
        span32: "Enabled",
        strong30: "Enquiries &amp; quotes",
        span33: "Enabled",
        strong31: "Bookings",
        span34: "Role based",
        p9: "Assign product access and operational responsibility by role.",
        small4: "Tour engine",
        h34: "Create once. Manage departures. Publish when ready.",
        span35: "Marketplace connected",
        h411: "Tour",
        strong32: "Kashmir Escape",
        p10: "5N/6D · Srinagar · Gulmarg · Pahalgam",
        h412: "Tour workspace",
        strong33: "Overview &amp; commercial",
        span36: "Complete",
        span37: "Ready",
        strong34: "Day-wise itinerary",
        span38: "6 days",
        span39: "Ready",
        strong35: "Hotels &amp; inclusions",
        span40: "Configured",
        span41: "Ready",
        strong36: "Departures &amp; capacity",
        span42: "3 active",
        span43: "Managed",
        h413: "Distribution principle",
        strong37: "Your operational inventory can become customer-facing inventory.",
        p11: "Approved tours are not trapped inside the partner portal—they can participate in the TravelsTREM marketplace where the agency is enrolled.",
        small5: "Customer workspace",
        h35: "Keep the requirement, conversation and next action together.",
        span44: "Ownership preserved",
        h414: "Enquiry pipeline",
        strong38: "Andaman family",
        span45: "4 travellers",
        span46: "New",
        strong39: "Kashmir honeymoon",
        span47: "2 travellers",
        span48: "Quoted",
        strong40: "Dubai holiday",
        span49: "5 travellers",
        span50: "Follow-up",
        strong41: "Leh adventure",
        span51: "8 travellers",
        span52: "Won",
        h415: "Customer context",
        strong42: "One journey",
        p12: "Requirements, assigned agent, tour reference, quote activity and booking status remain connected.",
        h416: "Designed for action",
        p13: "Instead of treating an enquiry as an isolated form submission, Partner TREM keeps it as the starting point of the customer lifecycle.",
        small6: "Quote engine",
        h36: "Build options around the traveller, not a static PDF.",
        span53: "Pricing controlled",
        h417: "Quote variants",
        strong43: "Standard",
        span54: "Hotels + transfers",
        span55: "₹72,500",
        strong44: "Premium",
        span56: "Upgraded stay + activities",
        span57: "₹89,900",
        strong45: "Advance",
        span58: "Flights + premium services",
        span59: "₹1,08,400",
        h418: "Final customer price",
        span60: "Agent quote",
        strong46: "₹85,000",
        span61: "TravelsTREM charges",
        strong47: "Applied",
        span62: "Taxes",
        strong48: "Calculated",
        span63: "Final payable",
        strong49: "₹89,900",
        p14: "Pricing logic can stay centrally governed instead of being duplicated in every product flow.",
        h419: "Quote lifecycle",
        p15: "Draft → send → customer reviews → revision if required → accept → proceed to payment. The quote remains part of the same customer journey.",
        small7: "Booking operations",
        h37: "A booking is not finished when payment succeeds.",
        span64: "Post-payment journey",
        h420: "Booking lifecycle",
        b1: "1",
        strong50: "Accepted",
        span65: "Chosen quote",
        b2: "2",
        strong51: "Advance paid",
        span66: "Booking secured",
        b3: "3",
        strong52: "Documents",
        span67: "Tickets &amp; passes",
        b4: "4",
        strong53: "Balance",
        span68: "Final settlement",
        b5: "5",
        strong54: "Completed",
        span69: "Journey delivered",
        h421: "Deliverables",
        strong55: "Flight tickets",
        span70: "Uploaded",
        span71: "Visible",
        strong56: "Hotel vouchers",
        span72: "Uploaded",
        span73: "Visible",
        strong57: "Travel insurance",
        span74: "Pending",
        span75: "Action",
        h422: "Customer view",
        strong58: "Everything in one booking.",
        p16: "Documents, payment progress and status can stay visible from the customer's dashboard.",
        small8: "Commercial records",
        h38: "Track collection, balance and booking value without losing context.",
        span76: "Auditable journey",
        h423: "Total booking value",
        strong59: "₹89,900",
        p17: "Final agreed customer amount.",
        h424: "Collected",
        strong60: "₹30,000",
        p18: "Advance payment received.",
        h425: "Balance",
        strong61: "₹59,900",
        p19: "Remaining settlement to collect.",
        h426: "Payment schedule",
        strong62: "Advance",
        span77: "Paid",
        span78: "₹30,000",
        strong63: "Second payment",
        span79: "Upcoming",
        span80: "₹30,000",
        strong64: "Final balance",
        span81: "Before departure",
        span82: "₹29,900",
        h427: "Monthly records",
        strong65: "Booking → payment → report",
        p20: "Operational records can feed agency-level reporting and future invoice summaries.",
      },
      sections_partnership_contact: {
        span1: "Travel or partnership",
        h21: "One platform. Two ways to start.",
        p1: "Explore a TravelsTREM product as a traveller, or speak with us about bringing your agency into the partner ecosystem.",
        a1: "Explore TravelsTREM ↗",
        a2: "Contact us",
      },
      sections_partnership_distribution: {
        span1: "A different kind of partner platform",
        h21: "Your back-office work can directly support your public distribution.",
        p1: "The partner portal is useful even before a marketplace booking arrives. The marketplace becomes an additional distribution layer—not a replacement for the agency.",
        span2: "Operate",
        h31: "Manage the agency you already have.",
        p2: "Agents, customers, tours, enquiries, quotes, bookings, payments and delivery records can live in a structured workspace instead of disconnected operational tools.",
        span3: "Distribute",
        h32: "Let eligible tours reach TravelsTREM travellers.",
        p3: "When a tour is ready and the agency is enrolled in the right product, the same inventory can become part of the customer-facing travel catalogue.",
        small1: "Marketplace status",
        strong1: "Kashmir Escape · Published",
        span4: "Trevista",
        span5: "5N/6D",
        span6: "Partner tour",
      },
      sections_partnership_hero: {
        span1: "Partner TREM · Agency operating workspace",
        h11: "Run the agency.",
        span2: "Connect the entire booking journey.",
        p1: "Partner TREM connects tour creation, enquiries, customers, quotes, bookings, payments and fulfilment in one operating workspace — with eligible inventory able to reach travellers through Trevista.",
        a1: "Apply for partnership ↗",
        a2: "Back to TravelsTREM",
        div1: "partner.travelstrem.com / overview",
        div2: "PartnerTREM",
        span3: "Overview",
        span4: "Enquiries",
        span5: "Tours",
        span6: "Quotes",
        span7: "Bookings",
        span8: "Payments",
        span9: "Customers",
        span10: "Reports",
        small1: "Agency workspace",
        strong1: "Good afternoon, Partner",
        span11: "Connected",
        small2: "Open enquiries",
        strong2: "18",
        em1: "Needs attention",
        small3: "Active quotes",
        strong3: "11",
        em2: "Across travellers",
        small4: "Live tours",
        strong4: "24",
        em3: "Marketplace ready",
        div3: "Customer journey",
        span12: "Today",
        div4: "AS",
        strong5: "Andaman family package",
        small5: "Quote revision requested",
        b1: "Quoted",
        div5: "RK",
        strong6: "Kashmir honeymoon",
        small6: "Advance payment received",
        b2: "Booked",
        div6: "NK",
        strong7: "Dubai holiday",
        small7: "Flight add-on pending",
        b3: "Enquiry",
        div7: "Booking activity",
        span13: "30 days",
        strong8: "Quote received ✓",
        small8: "The customer journey can move forward",
        strong9: "Tour published",
        small9: "Now visible in TravelsTREM",
        span14: "Agency team management",
        span15: "Tour management",
        span16: "Customer enquiries",
        span17: "Quote workflows",
        span18: "Booking lifecycle",
        span19: "Payment tracking",
        span20: "Partner marketplace",
        span21: "Role based operations",
        span22: "Agency team management",
        span23: "Tour management",
        span24: "Customer enquiries",
        span25: "Quote workflows",
        span26: "Booking lifecycle",
        span27: "Payment tracking",
        span28: "Partner marketplace",
        span29: "Role based operations",
      },
      sections_partnership_leadership: {
        span1: "The people behind the journey",
        h21: "Travel experience, business leadership and technology working together.",
        div1: "NG",
        p1: "Guides the organisation's culture of personal service, responsible stewardship and long-term direction.",
        div2: "SG",
        p2: "Leads Shree Air Tours &amp; Travels, its travel relationships and agency operations with more than two decades of industry experience.",
        div3: "AG",
        p3: "Leads TravelsTREM's product and technology vision across travellers, products and partner workflows.",
      },
      sections_partnership_platform: {
        span1: "Two sides. One connected platform.",
        h21: "Built for the traveller experience and the agency operating behind it.",
        p1: "Switch perspectives to see how the same platform serves both sides of the journey.",
        button1: "For travellers",
        button2: "For partner agencies",
      },
      sections_partnership_pricing: {
        span1: "Partner plans",
        h21: "Choose the plan that matches your agency's ambition.",
        p1: "Start with a focused operating workspace, then move up as your team, catalogue and customer relationships grow.",
        span2: "A confident start",
        p2: "For independent agencies ready to bring everyday sales and service into one place.",
        span3: "per month",
        li1: "One organised agency workspace",
        li2: "Tour and package publishing",
        li3: "Enquiry and quotation management",
        li4: "Clear customer booking visibility",
        a1: "Start your partnership →",
        span4: "Most popular",
        p3: "For growing teams coordinating more travellers, tours and sales opportunities.",
        span5: "per month",
        li5: "Everything in Partner Start",
        li6: "More team members with defined responsibilities",
        li7: "Expanded catalogue and distribution reach",
        li8: "Quote-to-booking business oversight",
        li9: "Agency performance visibility",
        a2: "Choose Partner Growth →",
        span6: "For established teams",
        p4: "For established agencies seeking greater capacity, support and operating control.",
        span7: "per month",
        li10: "Everything in Partner Growth",
        li11: "Greater team and catalogue capacity",
        li12: "Priority onboarding and business support",
        li13: "Deeper operating and performance views",
        li14: "Early access to new partner capabilities",
        a3: "Choose Partner Signature →",
        p5: "Monthly prices exclude applicable taxes. Plan inclusions are confirmed during partner onboarding.",
      },
      sections_partnership_workflow: {
        span1: "One continuous workflow",
        h21: "From “I’m interested” to “trip completed” without breaking the chain.",
        p1: "Every stage has an owner and every transition carries the context forward.",
        div1: "01",
        h31: "Discover",
        p2: "Traveller finds an eligible tour through a TravelsTREM product.",
        div2: "02",
        h32: "Enquire",
        p3: "Requirements reach the responsible partner and assigned agent.",
        div3: "03",
        h33: "Customise",
        p4: "The agent adapts the package to the traveller's actual requirement.",
        div4: "04",
        h34: "Quote",
        p5: "Variants are priced, shared, revised and accepted inside the journey.",
        div5: "05",
        h35: "Book &amp; pay",
        p6: "Payment secures the booking and creates the post-payment workflow.",
        div6: "06",
        h36: "Deliver",
        p7: "Tickets, vouchers, balances and trip status continue until completion.",
        strong1: "TREM = Tours → Reservations → Experience → Management",
        span2: "The product architecture follows the full operating journey—not just the checkout.",
        a1: "See Partner TREM ↑",
      },
    },
    products: {
      trehub: {
        status: "Flights & hotels",
        name: "TreHub",
        tagline: "Flight and hotel search connected to your journey",
        about:
          "TreHub brings flight and hotel search into the connected TravelsTREM journey. Compare fares, timings and stay options side by side, shortlist what fits, and keep it attached to the same trip so your enquiry and booking never lose context.",
        features: [
          "Flight options by fare, airline and timing",
          "Hotel stays with ratings, amenities and rates",
          "Side-by-side comparison and shortlist",
          "Connected enquiry and booking through TravelsTREM",
        ],
        linkKey: "trehub",
        cta: "Open TreHub ↗",
      },
      trevio: {
        status: "Community travel",
        name: "Trevio",
        tagline: "Community trips, adventures, treks and expeditions",
        about:
          "Trevio brings travellers together around shared departures. It covers community trips, treks, expeditions, events and travel communities, with a trip captain and a clear departure to keep every group organised.",
        features: [
          "Curated group adventures and travel communities",
          "Fixed departures with live seat availability",
          "Trip captains who run each departure",
          "Enquiries and bookings connected to your TravelsTREM account",
        ],
        linkKey: "trevio",
        cta: "Open Trevio ↗",
      },
      trevista: {
        status: "Tours & holidays",
        name: "Trevista",
        tagline: "Tours and holiday packages, personalised to you",
        about:
          "Trevista is the tours and holiday-packages product. Explore curated domestic and international journeys, review the itinerary and inclusions, and ask for a personalised version when the standard package is not exactly what you need.",
        features: [
          "Curated tour discovery with structured itineraries",
          "Detailed stays, inclusions and package options",
          "Personalised enquiry and quote journey",
          "Connected booking management through TravelsTREM",
        ],
        linkKey: "trevista",
        cta: "Open Trevista ↗",
      },
      hub: {
        status: "Connected account",
        name: "TravelsTREM Hub",
        tagline: "One account for the whole journey",
        about:
          "The TravelsTREM hub is the single account behind every product. It keeps discovery, enquiries, quotes, bookings, documents and support connected so you never lose context as your trip moves forward.",
        features: [
          "One TravelsTREM account across all products",
          "Enquiries, quotes and bookings in a single timeline",
          "Travel documents and booking progress together",
          "Support connected to every journey",
        ],
        linkKey: "hub",
        cta: "Open your dashboard ↗",
      },
      partnertrem: {
        status: "For travel agencies",
        name: "Partner TREM",
        tagline: "A workspace that runs the daily agency operation",
        about:
          "Partner TREM is the agency workspace behind TravelsTREM. It keeps tours, enquiries, customers and bookings in one place, and lets eligible journeys become discoverable by travellers through Trevista.",
        features: [
          "Role-based workspace for agency admins and agents",
          "Create, organise and publish structured tour inventory",
          "Manage enquiries, quotes and bookings with context",
          "Publish eligible tours to travellers through Trevista",
        ],
        linkKey: "partnerApplication",
        cta: "Apply for partnership ↗",
        detailsLinkKey: "partnershipDetails",
        detailsCta: "View details ↗",
      },
    },
    productPreviews: {
      trevio: [
        "Community Trips &amp; Adventures",
        "Shared departures, trip captains and travel communities",
        ["Overview", "Departures", "Community", "Captains"],
        "Featured departure",
        "Kedarkantha Winter Trek",
        [
          ["12", "Upcoming departures"],
          ["06", "Seats left"],
          ["4.9", "Community rating"],
        ],
        [
          ["Weekend trek · Kalsubai", "₹4,299 · Departure 18th"],
          ["Goa community trip", "Waitlist open"],
          ["Himalayan expedition", "Captain assigned"],
        ],
      ],
      trevista: [
        "Tours &amp; Packages",
        "Curated itineraries, personalised quotes, connected bookings",
        ["Overview", "Packages", "Itinerary", "Stays"],
        "Featured journey",
        "Royal Rajasthan Heritage Circuit",
        [
          ["6D", "Duration"],
          ["18", "Seats"],
          ["4.8", "Traveller rating"],
        ],
        [
          ["Standard package", "₹24,992"],
          ["Premium package", "₹36,536"],
          ["Custom journey", "Start enquiry"],
        ],
      ],
      trehub: [
        "Flights &amp; Hotels",
        "Search, compare and shortlist travel essentials in one view",
        ["Overview", "Flights", "Hotels", "Shortlist"],
        "Search · Jaipur → Delhi → Goa",
        "One comparison for travel essentials.",
        [
          ["14", "Flight options"],
          ["32", "Hotels found"],
          ["4.6", "Shortlist rating"],
        ],
        [
          ["IndiGo · 6E 2042 · 07:40", "₹4,899"],
          ["Vistara · UK 879 · 09:15", "₹5,420"],
          ["Hotel shortlist", "2 stays saved"],
        ],
      ],
    },
    audiences: {
      traveller: {
        title: "A journey that stays connected after you click “Get a Quote”.",
        copy: "Discover a tour, tell the responsible agent what you need, compare customised options, accept a quote, pay and continue receiving the documents and updates attached to the same booking.",
        benefits: [
          [
            "Discover",
            "Browse travel products and eligible tours without needing to understand the agency structure behind each listing.",
          ],
          [
            "Customise",
            "Your requirement becomes an actionable enquiry for the responsible agency and agent.",
          ],
          [
            "Continue",
            "Quote, payment, documents and booking status remain connected to the same journey.",
          ],
        ],
        visual: `
              <div class="journey-top"><div><small>Traveller journey</small><strong>Kashmir · 5 nights / 6 days</strong></div><span class="journey-status">Quote ready</span></div>
              <div class="journey-steps"><div class="journey-step"><b>1</b><strong>Discover</strong><span>Trevista</span></div><div class="journey-step"><b>2</b><strong>Enquire</strong><span>Requirements</span></div><div class="journey-step"><b>3</b><strong>Review</strong><span>Quote options</span></div><div class="journey-step"><b>4</b><strong>Pay</strong><span>Secure booking</span></div><div class="journey-step"><b>5</b><strong>Travel</strong><span>Documents</span></div></div>
              <div class="journey-card"><div class="journey-card-head"><div><small>Customised quote</small><strong>Choose the experience that fits you</strong></div><small>Valid for review</small></div><div class="quote-options"><div class="quote-option"><span>Standard</span><strong>₹72,500</strong></div><div class="quote-option active"><span>Premium</span><strong>₹89,900</strong></div><div class="quote-option"><span>Advance</span><strong>₹1,08,400</strong></div></div><div class="quote-total"><small>Final amount shown before payment</small><b>₹89,900</b></div></div>`,
      },
      partner: {
        title: "Run the agency workflow and publish into the same ecosystem.",
        copy: "Partner TREM gives approved agencies a structured operating surface for tours, customers, enquiries, quotes, bookings, payments and post-booking fulfilment—with eligible inventory connected to the TravelsTREM marketplace.",
        benefits: [
          ["Operate", "Manage agents, tours and customer journeys from one agency workspace."],
          [
            "Convert",
            "Turn enquiries into customised quotes and accepted bookings without losing context.",
          ],
          [
            "Distribute",
            "Publish eligible travel inventory into the TravelsTREM customer experience.",
          ],
        ],
        visual: `
              <div class="journey-top"><div><small>Partner TREM</small><strong>Agency operating journey</strong></div><span class="journey-status">Marketplace connected</span></div>
              <div class="journey-steps"><div class="journey-step"><b>1</b><strong>Tour</strong><span>Create</span></div><div class="journey-step"><b>2</b><strong>Publish</strong><span>Go live</span></div><div class="journey-step"><b>3</b><strong>Enquiry</strong><span>Assign</span></div><div class="journey-step"><b>4</b><strong>Quote</strong><span>Customise</span></div><div class="journey-step"><b>5</b><strong>Booking</strong><span>Deliver</span></div></div>
              <div class="journey-card"><div class="journey-card-head"><div><small>Agency queue</small><strong>What needs attention</strong></div><small>Live</small></div><div class="mini-table" style="color:var(--trem-text)"><div class="mini-row" style="background:var(--trem-surfaceSubtle)"><strong>Kashmir honeymoon</strong><span>Quote accepted</span><span class="status">Payment</span></div><div class="mini-row" style="background:var(--trem-surfaceSubtle)"><strong>Andaman family</strong><span>New enquiry</span><span class="status">Assign</span></div><div class="mini-row" style="background:var(--trem-surfaceSubtle)"><strong>Dubai holiday</strong><span>Booking</span><span class="status">Documents</span></div></div></div>`,
      },
    },
    pages: {
      home: {
        output: "index.html",
        frameStart: "src/pages/home/start.html",
        sections: [
          "src/sections/home/hero.html",
          "src/sections/home/marquee.html",
          "src/sections/home/promises.html",
          "src/sections/home/travellers.html",
          "src/sections/home/products.html",
          "src/sections/home/platform-preview.html",
          "src/sections/home/journey.html",
          "src/sections/home/quality.html",
          "src/sections/home/partner-trem.html",
          "src/sections/home/about.html",
          "src/sections/home/contact.html",
        ],
        frameEnd: "src/pages/home/end.html",
      },
      partnership: {
        output: "partnership.html",
        frameStart: "src/pages/partnership/start.html",
        sections: [
          "src/sections/partnership/hero.html",
          "src/sections/partnership/platform.html",
          "src/sections/partnership/capabilities.html",
          "src/sections/partnership/workflow.html",
          "src/sections/partnership/distribution.html",
          "src/sections/partnership/pricing.html",
          "src/sections/partnership/agency.html",
          "src/sections/partnership/leadership.html",
          "src/sections/partnership/contact.html",
        ],
        frameEnd: "src/pages/partnership/end.html",
      },
    },
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = TRAVELSTREM_WEBSITE;
  }

  if (!global?.document) return;

  const supplied = global.TRAVELSTREM_SITE_CONFIG || {};
  global.TRAVELSTREM_SITE_CONFIG = {
    ...TRAVELSTREM_WEBSITE,
    ...supplied,
    links: {
      ...TRAVELSTREM_WEBSITE.links,
      ...(supplied.links || {}),
    },
  };

  const applyConfiguredLinks = () => {
    document.querySelectorAll("a[data-link]").forEach((anchor) => {
      const destination = global.TRAVELSTREM_SITE_CONFIG.links?.[anchor.dataset.link];
      const link = typeof destination === "string" ? { href: destination } : destination;
      if (!link?.href) return;
      anchor.href =
        global.location?.protocol === "file:" && link.localHref ? link.localHref : link.href;
      if (link.external) {
        anchor.target = "_blank";
        anchor.rel = "noopener noreferrer";
      }
    });
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", applyConfiguredLinks, { once: true });
  } else {
    applyConfiguredLinks();
  }
})(typeof window !== "undefined" ? window : globalThis);
